using System;

public class BLEToyHLSequences
{
	public static BLEToyHLSequence SequenceForPhrase(BLEToyAudioPhrase phrase)
	{
		switch (phrase)
		{
		case BLEToyAudioPhrase.eP001:
			return BLEToyHLSequence.eHLS_Wake_1;
		case BLEToyAudioPhrase.eP002:
			return BLEToyHLSequence.eHLS_Wake_2;
		case BLEToyAudioPhrase.eP003:
			return BLEToyHLSequence.eHLS_App_alt_1;
		case BLEToyAudioPhrase.eP004:
			return BLEToyHLSequence.eHLS_Wake_4;
		case BLEToyAudioPhrase.eP005:
			return BLEToyHLSequence.eHLS_Wake_5;
		case BLEToyAudioPhrase.eP006:
			return BLEToyHLSequence.eHLS_IdlePhrase_27;
		case BLEToyAudioPhrase.eP008:
			return BLEToyHLSequence.eHLS_IdlePhrase_2;
		case BLEToyAudioPhrase.eP009:
			return BLEToyHLSequence.eHLS_IdlePhrase_3;
		case BLEToyAudioPhrase.eP010:
			return BLEToyHLSequence.eHLS_App_alt_2;
		case BLEToyAudioPhrase.eP011:
			return BLEToyHLSequence.eHLS_IdlePhrase_5;
		case BLEToyAudioPhrase.eP012:
			return BLEToyHLSequence.eHLS_IdlePhrase_6;
		case BLEToyAudioPhrase.eP013:
			return BLEToyHLSequence.eHLS_IdlePhrase_7;
		case BLEToyAudioPhrase.eP014:
			return BLEToyHLSequence.eHLS_IdlePhrase_8;
		case BLEToyAudioPhrase.eP015:
			return BLEToyHLSequence.eHLS_IdlePhrase_9;
		case BLEToyAudioPhrase.eP016:
			return BLEToyHLSequence.eHLS_IdlePhrase_10;
		case BLEToyAudioPhrase.eP017:
			return BLEToyHLSequence.eHLS_App_alt_3;
		case BLEToyAudioPhrase.eP018:
			return BLEToyHLSequence.eHLS_IdlePhrase_12;
		case BLEToyAudioPhrase.eP019:
			return BLEToyHLSequence.eHLS_IdlePhrase_13;
		case BLEToyAudioPhrase.eP020:
			return BLEToyHLSequence.eHLS_IdlePhrase_14;
		case BLEToyAudioPhrase.eP021:
			return BLEToyHLSequence.eHLS_IdlePhrase_15;
		case BLEToyAudioPhrase.eP022:
			return BLEToyHLSequence.eHLS_IdlePhrase_16;
		case BLEToyAudioPhrase.eP023:
			return BLEToyHLSequence.eHLS_IdlePhrase_17;
		case BLEToyAudioPhrase.eP024:
			return BLEToyHLSequence.eHLS_IdlePhrase_18;
		case BLEToyAudioPhrase.eP025:
			return BLEToyHLSequence.eHLS_IdlePhrase_19;
		case BLEToyAudioPhrase.eP026:
			return BLEToyHLSequence.eHLS_IdlePhrase_20;
		case BLEToyAudioPhrase.eP027:
			return BLEToyHLSequence.eHLS_App_alt_4;
		case BLEToyAudioPhrase.eP028:
			return BLEToyHLSequence.eHLS_IdlePhrase_22;
		case BLEToyAudioPhrase.eP029:
			return BLEToyHLSequence.eHLS_IdlePhrase_23;
		case BLEToyAudioPhrase.eP031:
			return BLEToyHLSequence.eHLS_IdleInstruct_1;
		case BLEToyAudioPhrase.eP032:
			return BLEToyHLSequence.eHLS_IdleInstruct_2;
		case BLEToyAudioPhrase.eP033:
			return BLEToyHLSequence.eHLS_App_alt_5;
		case BLEToyAudioPhrase.eP037:
			return BLEToyHLSequence.eHLS_Sleep_1;
		case BLEToyAudioPhrase.eP038:
			return BLEToyHLSequence.eHLS_Sleep_2;
		case BLEToyAudioPhrase.eP039:
			return BLEToyHLSequence.eHLS_Sleep_3;
		case BLEToyAudioPhrase.eP040:
			return BLEToyHLSequence.eHLS_Sleep_4;
		case BLEToyAudioPhrase.eP041:
			return BLEToyHLSequence.eHLS_Sleep_5;
		case BLEToyAudioPhrase.eP042:
			return BLEToyHLSequence.eHLS_Sleep_6;
		case BLEToyAudioPhrase.eP043:
			return BLEToyHLSequence.eHLS_Sleep_7;
		case BLEToyAudioPhrase.eP060:
			return BLEToyHLSequence.eHLS_ConnectStart_1;
		case BLEToyAudioPhrase.eP061:
			return BLEToyHLSequence.eHLS_ConnectStart_2;
		case BLEToyAudioPhrase.eP062:
			return BLEToyHLSequence.eHLS_ConnectStart_3;
		case BLEToyAudioPhrase.eP063:
			return BLEToyHLSequence.eHLS_ConnectStart_4;
		case BLEToyAudioPhrase.eP064:
			return BLEToyHLSequence.eHLS_ConnectStart_5;
		case BLEToyAudioPhrase.eP065:
			return BLEToyHLSequence.eHLS_App_alt_26;
		case BLEToyAudioPhrase.eP066:
			return BLEToyHLSequence.eHLS_App_alt_27;
		case BLEToyAudioPhrase.eP067:
			return BLEToyHLSequence.eHLS_App_alt_28;
		case BLEToyAudioPhrase.eP068:
			return BLEToyHLSequence.eHLS_App_alt_29;
		case BLEToyAudioPhrase.eP069:
			return BLEToyHLSequence.eHLS_App_alt_30;
		case BLEToyAudioPhrase.eP070:
			return BLEToyHLSequence.eHLS_DanceIntro_1;
		case BLEToyAudioPhrase.eP071:
			return BLEToyHLSequence.eHLS_DanceIntro_2;
		case BLEToyAudioPhrase.eP072:
			return BLEToyHLSequence.eHLS_DanceIntro_3;
		case BLEToyAudioPhrase.eP084:
			return BLEToyHLSequence.eHLS_DanceInstruct_1;
		case BLEToyAudioPhrase.eP085:
			return BLEToyHLSequence.eHLS_DanceInstruct_1First;
		case BLEToyAudioPhrase.eP086:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Final;
		case BLEToyAudioPhrase.eP087:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Then;
		case BLEToyAudioPhrase.eP088:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Like;
		case BLEToyAudioPhrase.eP089:
			return BLEToyHLSequence.eHLS_DanceInstruct_1_ALTA;
		case BLEToyAudioPhrase.eP090:
			return BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTA;
		case BLEToyAudioPhrase.eP091:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTA;
		case BLEToyAudioPhrase.eP092:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTA;
		case BLEToyAudioPhrase.eP093:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Like_ALTA;
		case BLEToyAudioPhrase.eP094:
			return BLEToyHLSequence.eHLS_DanceInstruct_1_ALTB;
		case BLEToyAudioPhrase.eP095:
			return BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTB;
		case BLEToyAudioPhrase.eP096:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTB;
		case BLEToyAudioPhrase.eP097:
			return BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTB;
		case BLEToyAudioPhrase.eP098:
			return BLEToyHLSequence.eHLS_DanceInstruct_2;
		case BLEToyAudioPhrase.eP099:
			return BLEToyHLSequence.eHLS_DanceInstruct_2First;
		case BLEToyAudioPhrase.eP100:
			return BLEToyHLSequence.eHLS_DanceInstruct_2Final;
		case BLEToyAudioPhrase.eP101:
			return BLEToyHLSequence.eHLS_DanceInstruct_2Then;
		case BLEToyAudioPhrase.eP102:
			return BLEToyHLSequence.eHLS_DanceInstruct_2Like;
		case BLEToyAudioPhrase.eP103:
			return BLEToyHLSequence.eHLS_DanceInstruct_3;
		case BLEToyAudioPhrase.eP104:
			return BLEToyHLSequence.eHLS_DanceInstruct_3First;
		case BLEToyAudioPhrase.eP105:
			return BLEToyHLSequence.eHLS_DanceInstruct_3Final;
		case BLEToyAudioPhrase.eP106:
			return BLEToyHLSequence.eHLS_DanceInstruct_3Then;
		case BLEToyAudioPhrase.eP107:
			return BLEToyHLSequence.eHLS_DanceInstruct_3Like;
		case BLEToyAudioPhrase.eP108:
			return BLEToyHLSequence.eHLS_DanceInstruct_4;
		case BLEToyAudioPhrase.eP109:
			return BLEToyHLSequence.eHLS_DanceInstruct_4First;
		case BLEToyAudioPhrase.eP110:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Final;
		case BLEToyAudioPhrase.eP111:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Next;
		case BLEToyAudioPhrase.eP112:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Like;
		case BLEToyAudioPhrase.eP113:
			return BLEToyHLSequence.eHLS_DanceInstruct_4_ALT;
		case BLEToyAudioPhrase.eP114:
			return BLEToyHLSequence.eHLS_DanceInstruct_4First_ALT;
		case BLEToyAudioPhrase.eP115:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Final_ALT;
		case BLEToyAudioPhrase.eP116:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Next_ALT;
		case BLEToyAudioPhrase.eP117:
			return BLEToyHLSequence.eHLS_DanceInstruct_4Like_ALT;
		case BLEToyAudioPhrase.eP118:
			return BLEToyHLSequence.eHLS_DanceInstruct_5;
		case BLEToyAudioPhrase.eP119:
			return BLEToyHLSequence.eHLS_DanceInstruct_5First;
		case BLEToyAudioPhrase.eP120:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Final;
		case BLEToyAudioPhrase.eP121:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Then;
		case BLEToyAudioPhrase.eP122:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Like;
		case BLEToyAudioPhrase.eP123:
			return BLEToyHLSequence.eHLS_DanceInstruct_5_ALTA;
		case BLEToyAudioPhrase.eP124:
			return BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTA;
		case BLEToyAudioPhrase.eP125:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTA;
		case BLEToyAudioPhrase.eP126:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTA;
		case BLEToyAudioPhrase.eP127:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTA;
		case BLEToyAudioPhrase.eP128:
			return BLEToyHLSequence.eHLS_DanceInstruct_5_ALTB;
		case BLEToyAudioPhrase.eP129:
			return BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTB;
		case BLEToyAudioPhrase.eP130:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTB;
		case BLEToyAudioPhrase.eP131:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTB;
		case BLEToyAudioPhrase.eP132:
			return BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTB;
		case BLEToyAudioPhrase.eP133:
			return BLEToyHLSequence.eHLS_DanceInstruct_6;
		case BLEToyAudioPhrase.eP134:
			return BLEToyHLSequence.eHLS_DanceInstruct_6First;
		case BLEToyAudioPhrase.eP135:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Final;
		case BLEToyAudioPhrase.eP136:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Next;
		case BLEToyAudioPhrase.eP137:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Like;
		case BLEToyAudioPhrase.eP138:
			return BLEToyHLSequence.eHLS_DanceInstruct_6_ALT;
		case BLEToyAudioPhrase.eP139:
			return BLEToyHLSequence.eHLS_DanceInstruct_6First_ALT;
		case BLEToyAudioPhrase.eP140:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Final_ALT;
		case BLEToyAudioPhrase.eP141:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Next_ALT;
		case BLEToyAudioPhrase.eP142:
			return BLEToyHLSequence.eHLS_DanceInstruct_6Like_ALT;
		case BLEToyAudioPhrase.eP143:
			return BLEToyHLSequence.eHLS_DanceInstruct_7;
		case BLEToyAudioPhrase.eP144:
			return BLEToyHLSequence.eHLS_DanceInstruct_7First;
		case BLEToyAudioPhrase.eP145:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Final;
		case BLEToyAudioPhrase.eP146:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Then;
		case BLEToyAudioPhrase.eP147:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Like;
		case BLEToyAudioPhrase.eP148:
			return BLEToyHLSequence.eHLS_DanceInstruct_7_ALTA;
		case BLEToyAudioPhrase.eP149:
			return BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTA;
		case BLEToyAudioPhrase.eP150:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTA;
		case BLEToyAudioPhrase.eP151:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTA;
		case BLEToyAudioPhrase.eP152:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTA;
		case BLEToyAudioPhrase.eP153:
			return BLEToyHLSequence.eHLS_DanceInstruct_7_ALTB;
		case BLEToyAudioPhrase.eP154:
			return BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTB;
		case BLEToyAudioPhrase.eP155:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTB;
		case BLEToyAudioPhrase.eP156:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTB;
		case BLEToyAudioPhrase.eP157:
			return BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTB;
		case BLEToyAudioPhrase.eP158:
			return BLEToyHLSequence.eHLS_DanceInstruct_8;
		case BLEToyAudioPhrase.eP159:
			return BLEToyHLSequence.eHLS_DanceInstruct_8First;
		case BLEToyAudioPhrase.eP160:
			return BLEToyHLSequence.eHLS_DanceInstruct_8Final;
		case BLEToyAudioPhrase.eP161:
			return BLEToyHLSequence.eHLS_DanceInstruct_8Next;
		case BLEToyAudioPhrase.eP162:
			return BLEToyHLSequence.eHLS_DanceInstruct_8Like;
		case BLEToyAudioPhrase.eP163:
			return BLEToyHLSequence.eHLS_DanceInstruct_9;
		case BLEToyAudioPhrase.eP164:
			return BLEToyHLSequence.eHLS_DanceInstruct_9First;
		case BLEToyAudioPhrase.eP165:
			return BLEToyHLSequence.eHLS_DanceInstruct_9Final;
		case BLEToyAudioPhrase.eP166:
			return BLEToyHLSequence.eHLS_DanceInstruct_9Then;
		case BLEToyAudioPhrase.eP167:
			return BLEToyHLSequence.eHLS_DanceInstruct_9Like;
		case BLEToyAudioPhrase.eP168:
			return BLEToyHLSequence.eHLS_DanceInstruct_10;
		case BLEToyAudioPhrase.eP169:
			return BLEToyHLSequence.eHLS_DanceInstruct_10First;
		case BLEToyAudioPhrase.eP170:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Final;
		case BLEToyAudioPhrase.eP171:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Next;
		case BLEToyAudioPhrase.eP172:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Like;
		case BLEToyAudioPhrase.eP173:
			return BLEToyHLSequence.eHLS_DanceInstruct_10_ALT;
		case BLEToyAudioPhrase.eP174:
			return BLEToyHLSequence.eHLS_DanceInstruct_10First_ALT;
		case BLEToyAudioPhrase.eP175:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Final_ALT;
		case BLEToyAudioPhrase.eP176:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Next_ALT;
		case BLEToyAudioPhrase.eP176b:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Next_ALTb;
		case BLEToyAudioPhrase.eP177:
			return BLEToyHLSequence.eHLS_DanceInstruct_10Like_ALT;
		case BLEToyAudioPhrase.eP178:
			return BLEToyHLSequence.eHLS_DanceInstruct_11;
		case BLEToyAudioPhrase.eP179:
			return BLEToyHLSequence.eHLS_DanceInstruct_11First;
		case BLEToyAudioPhrase.eP180:
			return BLEToyHLSequence.eHLS_DanceInstruct_11Final;
		case BLEToyAudioPhrase.eP181:
			return BLEToyHLSequence.eHLS_DanceInstruct_11Then;
		case BLEToyAudioPhrase.eP182:
			return BLEToyHLSequence.eHLS_DanceInstruct_11Like;
		case BLEToyAudioPhrase.eP183:
			return BLEToyHLSequence.eHLS_DanceInstruct_Spin_1;
		case BLEToyAudioPhrase.eP184:
			return BLEToyHLSequence.eHLS_DanceInstruct_Spin_1_ALT;
		case BLEToyAudioPhrase.eP185:
			return BLEToyHLSequence.eHLS_DanceInstruct_RS_1;
		case BLEToyAudioPhrase.eP186:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1;
		case BLEToyAudioPhrase.eP187:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1;
		case BLEToyAudioPhrase.eP188:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1;
		case BLEToyAudioPhrase.eP189:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1;
		case BLEToyAudioPhrase.eP190:
			return BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTA;
		case BLEToyAudioPhrase.eP191:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1B;
		case BLEToyAudioPhrase.eP192:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1B;
		case BLEToyAudioPhrase.eP193:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTA;
		case BLEToyAudioPhrase.eP194:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTA;
		case BLEToyAudioPhrase.eP195:
			return BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTB;
		case BLEToyAudioPhrase.eP196:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1C;
		case BLEToyAudioPhrase.eP197:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1C;
		case BLEToyAudioPhrase.eP198:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTB;
		case BLEToyAudioPhrase.eP199:
			return BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTB;
		case BLEToyAudioPhrase.eP200:
			return BLEToyHLSequence.eHLS_DanceInstruct_SpinAgain_1;
		case BLEToyAudioPhrase.eP201:
			return BLEToyHLSequence.eHLS_DanceInstruct_SpinOther_1;
		case BLEToyAudioPhrase.eP202:
			return BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1;
		case BLEToyAudioPhrase.eP203:
			return BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1_ALT;
		case BLEToyAudioPhrase.eP204:
			return BLEToyHLSequence.eHLS_DanceInstruct_Fwd_1;
		case BLEToyAudioPhrase.eP205:
			return BLEToyHLSequence.eHLS_DanceInstruct_FwdFirst_1;
		case BLEToyAudioPhrase.eP206:
			return BLEToyHLSequence.eHLS_DanceInstruct_FwdFinal_1;
		case BLEToyAudioPhrase.eP207:
			return BLEToyHLSequence.eHLS_DanceInstruct_FwdNow_1;
		case BLEToyAudioPhrase.eP208:
			return BLEToyHLSequence.eHLS_DanceInstruct_FwdThen_1;
		case BLEToyAudioPhrase.eP208b:
			return BLEToyHLSequence.eHLS_DanceInstruct_FwdThen_1b;
		case BLEToyAudioPhrase.eP209:
			return BLEToyHLSequence.eHLS_DanceInstruct_Back_1;
		case BLEToyAudioPhrase.eP210:
			return BLEToyHLSequence.eHLS_DanceInstruct_BackFirst_1;
		case BLEToyAudioPhrase.eP211:
			return BLEToyHLSequence.eHLS_DanceInstruct_BackFinal_1;
		case BLEToyAudioPhrase.eP212:
			return BLEToyHLSequence.eHLS_DanceInstruct_BackNow_1;
		case BLEToyAudioPhrase.eP213:
			return BLEToyHLSequence.eHLS_DanceInstruct_BackThen_1;
		case BLEToyAudioPhrase.eP214:
			return BLEToyHLSequence.eHLS_DanceInstruct_Turn_1;
		case BLEToyAudioPhrase.eP215:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1;
		case BLEToyAudioPhrase.eP216:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1;
		case BLEToyAudioPhrase.eP217:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1;
		case BLEToyAudioPhrase.eP218:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1;
		case BLEToyAudioPhrase.eP219:
			return BLEToyHLSequence.eHLS_DanceInstruct_Turn_1_ALT;
		case BLEToyAudioPhrase.eP220:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1_ALT;
		case BLEToyAudioPhrase.eP221:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1_ALT;
		case BLEToyAudioPhrase.eP222:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1_ALT;
		case BLEToyAudioPhrase.eP223:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1_ALT;
		case BLEToyAudioPhrase.eP224:
			return BLEToyHLSequence.eHLS_DanceInstruct_FaceFwd_1;
		case BLEToyAudioPhrase.eP225:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1;
		case BLEToyAudioPhrase.eP226:
			return BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1_ALT;
		case BLEToyAudioPhrase.eP227:
			return BLEToyHLSequence.eHLS_DanceInstruct_Arms_1;
		case BLEToyAudioPhrase.eP227b:
			return BLEToyHLSequence.eHLS_DanceInstruct_Arms_1b;
		case BLEToyAudioPhrase.eP228:
			return BLEToyHLSequence.eHLS_DanceInstruct_ArmsFirst_1;
		case BLEToyAudioPhrase.eP229:
			return BLEToyHLSequence.eHLS_DanceInstruct_ArmsNow_1;
		case BLEToyAudioPhrase.eP230:
			return BLEToyHLSequence.eHLS_DanceInstruct_ArmsThen_1;
		case BLEToyAudioPhrase.eP231:
			return BLEToyHLSequence.eHLS_DanceInstruct_ArmsFinal_1;
		case BLEToyAudioPhrase.eP232:
			return BLEToyHLSequence.eHLS_DanceInstruct_Move_1;
		case BLEToyAudioPhrase.eP233:
			return BLEToyHLSequence.eHLS_DanceInstruct_MoveFirst_1;
		case BLEToyAudioPhrase.eP234:
			return BLEToyHLSequence.eHLS_DanceInstruct_MoveNow_1;
		case BLEToyAudioPhrase.eP235:
			return BLEToyHLSequence.eHLS_DanceInstruct_MoveThen_1;
		case BLEToyAudioPhrase.eP236:
			return BLEToyHLSequence.eHLS_DanceInstruct_MoveFinal_1;
		case BLEToyAudioPhrase.eP237:
			return BLEToyHLSequence.eHLS_DanceInstruct_Perform_1;
		case BLEToyAudioPhrase.eP238:
			return BLEToyHLSequence.eHLS_DanceInstruct_Perform_2;
		case BLEToyAudioPhrase.eP239:
			return BLEToyHLSequence.eHLS_DanceInstruct_Perform_3;
		case BLEToyAudioPhrase.eP240:
			return BLEToyHLSequence.eHLS_DanceInstruct_Generic_1;
		case BLEToyAudioPhrase.eP241:
			return BLEToyHLSequence.eHLS_DanceInstruct_Generic_2;
		case BLEToyAudioPhrase.eP242:
			return BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1;
		case BLEToyAudioPhrase.eP243:
			return BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1_ALT;
		case BLEToyAudioPhrase.eP244:
			return BLEToyHLSequence.eHLS_DanceInstruct_Connect_1;
		case BLEToyAudioPhrase.eP244b:
			return BLEToyHLSequence.eHLS_DanceInstruct_Connect_1b;
		case BLEToyAudioPhrase.eP244c:
			return BLEToyHLSequence.eHLS_DanceInstruct_Connect_1c;
		case BLEToyAudioPhrase.eP245:
			return BLEToyHLSequence.eHLS_Encourage_1;
		case BLEToyAudioPhrase.eP246:
			return BLEToyHLSequence.eHLS_Encourage_2;
		case BLEToyAudioPhrase.eP247:
			return BLEToyHLSequence.eHLS_Encourage_3;
		case BLEToyAudioPhrase.eP248:
			return BLEToyHLSequence.eHLS_Encourage_4;
		case BLEToyAudioPhrase.eP249:
			return BLEToyHLSequence.eHLS_Encourage_5;
		case BLEToyAudioPhrase.eP250:
			return BLEToyHLSequence.eHLS_Encourage_6;
		case BLEToyAudioPhrase.eP251:
			return BLEToyHLSequence.eHLS_Encourage_7;
		case BLEToyAudioPhrase.eP252:
			return BLEToyHLSequence.eHLS_PerformAgainPrompt_1;
		case BLEToyAudioPhrase.eP253:
			return BLEToyHLSequence.eHLS_PerformAgainPrompt_2;
		case BLEToyAudioPhrase.eP254:
			return BLEToyHLSequence.eHLS_PerformAgainPrompt_3;
		case BLEToyAudioPhrase.eP255:
			return BLEToyHLSequence.eHLS_App_alt_8;
		case BLEToyAudioPhrase.eP256:
			return BLEToyHLSequence.eHLS_App_alt_9;
		case BLEToyAudioPhrase.eP257:
			return BLEToyHLSequence.eHLS_App_alt_10;
		case BLEToyAudioPhrase.eP258:
			return BLEToyHLSequence.eHLS_App_alt_11;
		case BLEToyAudioPhrase.eP259:
			return BLEToyHLSequence.eHLS_App_alt_12;
		case BLEToyAudioPhrase.eP262:
			return BLEToyHLSequence.eHLS_DanceTogether_3;
		case BLEToyAudioPhrase.eP263:
			return BLEToyHLSequence.eHLS_DanceTogether_4;
		case BLEToyAudioPhrase.eP264:
			return BLEToyHLSequence.eHLS_DanceTogether_5;
		case BLEToyAudioPhrase.eP265:
			return BLEToyHLSequence.eHLS_DanceTogether_6;
		case BLEToyAudioPhrase.eP266:
			return BLEToyHLSequence.eHLS_DanceTogether_7;
		case BLEToyAudioPhrase.eP267:
			return BLEToyHLSequence.eHLS_DanceTogether_8;
		case BLEToyAudioPhrase.eP268:
			return BLEToyHLSequence.eHLS_DanceBreak_1;
		case BLEToyAudioPhrase.eP269:
			return BLEToyHLSequence.eHLS_DanceBreak_2;
		case BLEToyAudioPhrase.eP270:
			return BLEToyHLSequence.eHLS_LiftPhrase_1;
		case BLEToyAudioPhrase.eP271:
			return BLEToyHLSequence.eHLS_LiftPhrase_2;
		case BLEToyAudioPhrase.eP272:
			return BLEToyHLSequence.eHLS_App_alt_13;
		case BLEToyAudioPhrase.eP273:
			return BLEToyHLSequence.eHLS_LiftPhrase_4;
		case BLEToyAudioPhrase.eP274:
			return BLEToyHLSequence.eHLS_LiftPhrase_5;
		case BLEToyAudioPhrase.eP275:
			return BLEToyHLSequence.eHLS_App_alt_14;
		case BLEToyAudioPhrase.eP260:
			return BLEToyHLSequence.eHLS_DanceTogether_1;
		case BLEToyAudioPhrase.eP261:
			return BLEToyHLSequence.eHLS_DanceTogether_2;
		case BLEToyAudioPhrase.eP276:
			return BLEToyHLSequence.eHLS_AppConnect_1;
		case BLEToyAudioPhrase.eP277:
			return BLEToyHLSequence.eHLS_ButtonPress_1;
		case BLEToyAudioPhrase.eP278:
			return BLEToyHLSequence.eHLS_SleepButtonPress_1;
		case BLEToyAudioPhrase.eP279:
			return BLEToyHLSequence.eHLS_DanceRoutine_1;
		case BLEToyAudioPhrase.eP280:
			return BLEToyHLSequence.eHLS_DanceRoutine_2;
		case BLEToyAudioPhrase.eP281:
			return BLEToyHLSequence.eHLS_DanceRoutine_3;
		case BLEToyAudioPhrase.eP282:
			return BLEToyHLSequence.eHLS_DanceRoutine_4;
		case BLEToyAudioPhrase.eP283:
			return BLEToyHLSequence.eHLS_DanceRoutine_5;
		case BLEToyAudioPhrase.eP284:
			return BLEToyHLSequence.eHLS_DanceRoutine_6;
		case BLEToyAudioPhrase.eP285:
			return BLEToyHLSequence.eHLS_DanceRoutine_7;
		case BLEToyAudioPhrase.eP286:
			return BLEToyHLSequence.eHLS_DanceRoutine_8;
		case BLEToyAudioPhrase.eP287:
			return BLEToyHLSequence.eHLS_DanceRoutine_9;
		case BLEToyAudioPhrase.eP288:
			return BLEToyHLSequence.eHLS_DanceRoutine_10;
		case BLEToyAudioPhrase.eP303:
			return BLEToyHLSequence.eHLS_App_alt_15;
		case BLEToyAudioPhrase.eP304:
			return BLEToyHLSequence.eHLS_App_alt_16;
		case BLEToyAudioPhrase.eP305:
			return BLEToyHLSequence.eHLS_App_alt_17;
		case BLEToyAudioPhrase.eP306:
			return BLEToyHLSequence.eHLS_App_alt_18;
		case BLEToyAudioPhrase.eP307:
			return BLEToyHLSequence.eHLS_App_alt_19;
		case BLEToyAudioPhrase.eP308:
			return BLEToyHLSequence.eHLS_App_alt_20;
		case BLEToyAudioPhrase.eP309:
			return BLEToyHLSequence.eHLS_App_alt_21;
		case BLEToyAudioPhrase.eP310:
			return BLEToyHLSequence.eHLS_App_alt_22;
		case BLEToyAudioPhrase.eP311:
			return BLEToyHLSequence.eHLS_App_alt_23;
		case BLEToyAudioPhrase.eP312:
			return BLEToyHLSequence.eHLS_App_alt_24;
		case BLEToyAudioPhrase.eP313:
			return BLEToyHLSequence.eHLS_LessonPerformIntro_2;
		case BLEToyAudioPhrase.eP314:
			return BLEToyHLSequence.eHLS_LessonPerformIntro_3;
		case BLEToyAudioPhrase.eP315:
			return BLEToyHLSequence.eHLS_LessonPerformIntro_4;
		case BLEToyAudioPhrase.eP316:
			return BLEToyHLSequence.eHLS_App_alt_25;
		case BLEToyAudioPhrase.eP317:
			return BLEToyHLSequence.eHLS_LessonPerformIntro_6;
		case BLEToyAudioPhrase.eP318:
			return BLEToyHLSequence.eHLS_ShortInstruct_1;
		case BLEToyAudioPhrase.eP319:
			return BLEToyHLSequence.eHLS_ShortInstruct_1_ALTA;
		case BLEToyAudioPhrase.eP320:
			return BLEToyHLSequence.eHLS_ShortInstruct_2;
		case BLEToyAudioPhrase.eP321:
			return BLEToyHLSequence.eHLS_ShortInstruct_3;
		case BLEToyAudioPhrase.eP322:
			return BLEToyHLSequence.eHLS_ShortInstruct_4;
		case BLEToyAudioPhrase.eP323:
			return BLEToyHLSequence.eHLS_ShortInstruct_4_ALT;
		case BLEToyAudioPhrase.eP324:
			return BLEToyHLSequence.eHLS_ShortInstruct_5;
		case BLEToyAudioPhrase.eP325:
			return BLEToyHLSequence.eHLS_ShortInstruct_6;
		case BLEToyAudioPhrase.eP326:
			return BLEToyHLSequence.eHLS_ShortInstruct_7;
		case BLEToyAudioPhrase.eP327:
			return BLEToyHLSequence.eHLS_ShortInstruct_8;
		case BLEToyAudioPhrase.eP328:
			return BLEToyHLSequence.eHLS_ShortInstruct_9;
		case BLEToyAudioPhrase.eP329:
			return BLEToyHLSequence.eHLS_ShortInstruct_10_ALT;
		case BLEToyAudioPhrase.eP330:
			return BLEToyHLSequence.eHLS_ShortInstruct_Spin_1;
		case BLEToyAudioPhrase.eP331:
			return BLEToyHLSequence.eHLS_ShortInstruct_Spin_1_ALT;
		case BLEToyAudioPhrase.eP332:
			return BLEToyHLSequence.eHLS_ShortInstruct_SpinAgain_1;
		case BLEToyAudioPhrase.eP333:
			return BLEToyHLSequence.eHLS_ShortInstruct_SpinOther_1;
		case BLEToyAudioPhrase.eP334:
			return BLEToyHLSequence.eHLS_ShortInstruct_FaceFwd_1;
		case BLEToyAudioPhrase.eP335:
			return BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1;
		case BLEToyAudioPhrase.eP336:
			return BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1_ALT;
		case BLEToyAudioPhrase.eP337:
			return BLEToyHLSequence.eHLS_ShortInstruct_Move_1;
		case BLEToyAudioPhrase.eP338:
			return BLEToyHLSequence.eHLS_IdleInstruct_4;
		case BLEToyAudioPhrase.eP339:
			return BLEToyHLSequence.eHLS_App_alt_6;
		case BLEToyAudioPhrase.eP339b:
			return BLEToyHLSequence.eHLS_IdleInstruct_9;
		case BLEToyAudioPhrase.eP340:
			return BLEToyHLSequence.eHLS_IdleInstruct_6;
		case BLEToyAudioPhrase.eP341:
			return BLEToyHLSequence.eHLS_IdleInstruct_7;
		case BLEToyAudioPhrase.eP342:
			return BLEToyHLSequence.eHLS_App_alt_7;
		case BLEToyAudioPhrase.eP700:
			return BLEToyHLSequence.eHLS_App_Phrase_1;
		case BLEToyAudioPhrase.eP701:
			return BLEToyHLSequence.eHLS_App_Phrase_2;
		case BLEToyAudioPhrase.eP702:
			return BLEToyHLSequence.eHLS_App_Phrase_3;
		case BLEToyAudioPhrase.eP703:
			return BLEToyHLSequence.eHLS_App_Phrase_4;
		case BLEToyAudioPhrase.eP704:
			return BLEToyHLSequence.eHLS_App_Phrase_5;
		case BLEToyAudioPhrase.eP705:
			return BLEToyHLSequence.eHLS_App_Phrase_6;
		case BLEToyAudioPhrase.eP706:
			return BLEToyHLSequence.eHLS_App_Phrase_7;
		case BLEToyAudioPhrase.eP707:
			return BLEToyHLSequence.eHLS_App_Phrase_8;
		case BLEToyAudioPhrase.eP708:
			return BLEToyHLSequence.eHLS_App_Phrase_9;
		case BLEToyAudioPhrase.eP709:
			return BLEToyHLSequence.eHLS_App_Phrase_10;
		case BLEToyAudioPhrase.eP710:
			return BLEToyHLSequence.eHLS_App_Phrase_11;
		case BLEToyAudioPhrase.eP711:
			return BLEToyHLSequence.eHLS_App_Phrase_12;
		case BLEToyAudioPhrase.eP712:
			return BLEToyHLSequence.eHLS_App_Phrase_13;
		case BLEToyAudioPhrase.eP713:
			return BLEToyHLSequence.eHLS_App_Phrase_14;
		case BLEToyAudioPhrase.eP714:
			return BLEToyHLSequence.eHLS_App_Phrase_15;
		case BLEToyAudioPhrase.eP715:
			return BLEToyHLSequence.eHLS_App_Phrase_16;
		case BLEToyAudioPhrase.eP716:
			return BLEToyHLSequence.eHLS_App_Phrase_17;
		case BLEToyAudioPhrase.eP717:
			return BLEToyHLSequence.eHLS_App_Phrase_18;
		case BLEToyAudioPhrase.eP718:
			return BLEToyHLSequence.eHLS_App_Phrase_19;
		case BLEToyAudioPhrase.eP719:
			return BLEToyHLSequence.eHLS_App_Phrase_20;
		case BLEToyAudioPhrase.eP720:
			return BLEToyHLSequence.eHLS_App_Phrase_21;
		case BLEToyAudioPhrase.eP721:
			return BLEToyHLSequence.eHLS_App_Phrase_22;
		case BLEToyAudioPhrase.eP722:
			return BLEToyHLSequence.eHLS_App_Phrase_23;
		case BLEToyAudioPhrase.eP723:
			return BLEToyHLSequence.eHLS_App_Phrase_24;
		case BLEToyAudioPhrase.eP724:
			return BLEToyHLSequence.eHLS_App_Phrase_25;
		case BLEToyAudioPhrase.eP725:
			return BLEToyHLSequence.eHLS_App_Phrase_26;
		case BLEToyAudioPhrase.eP726:
			return BLEToyHLSequence.eHLS_App_Phrase_27;
		case BLEToyAudioPhrase.eP727:
			return BLEToyHLSequence.eHLS_App_Phrase_28;
		case BLEToyAudioPhrase.eP728:
			return BLEToyHLSequence.eHLS_App_Phrase_29;
		case BLEToyAudioPhrase.eP729:
			return BLEToyHLSequence.eHLS_App_Phrase_30;
		case BLEToyAudioPhrase.eP730:
			return BLEToyHLSequence.eHLS_App_Phrase_31;
		case BLEToyAudioPhrase.eP731:
			return BLEToyHLSequence.eHLS_App_Phrase_32;
		case BLEToyAudioPhrase.eP732:
			return BLEToyHLSequence.eHLS_App_Phrase_33;
		case BLEToyAudioPhrase.eP733:
			return BLEToyHLSequence.eHLS_App_Phrase_34;
		case BLEToyAudioPhrase.eP733B:
			return BLEToyHLSequence.eHLS_App_Phrase_34_alt1;
		case BLEToyAudioPhrase.eP733C:
			return BLEToyHLSequence.eHLS_App_Phrase_34_alt2;
		case BLEToyAudioPhrase.eP734:
			return BLEToyHLSequence.eHLS_App_Phrase_35;
		case BLEToyAudioPhrase.eP735:
			return BLEToyHLSequence.eHLS_App_Phrase_36;
		case BLEToyAudioPhrase.eP736:
			return BLEToyHLSequence.eHLS_App_Phrase_37;
		case BLEToyAudioPhrase.eP737:
			return BLEToyHLSequence.eHLS_App_Phrase_38;
		case BLEToyAudioPhrase.eP738:
			return BLEToyHLSequence.eHLS_App_Phrase_39;
		case BLEToyAudioPhrase.eP739:
			return BLEToyHLSequence.eHLS_App_Phrase_40;
		case BLEToyAudioPhrase.eP740:
			return BLEToyHLSequence.eHLS_App_Phrase_41;
		case BLEToyAudioPhrase.eP741:
			return BLEToyHLSequence.eHLS_App_Phrase_42;
		case BLEToyAudioPhrase.eP742:
			return BLEToyHLSequence.eHLS_App_Phrase_43;
		case BLEToyAudioPhrase.eP743:
			return BLEToyHLSequence.eHLS_App_Phrase_44;
		case BLEToyAudioPhrase.eP744:
			return BLEToyHLSequence.eHLS_App_Phrase_45;
		case BLEToyAudioPhrase.eP745:
			return BLEToyHLSequence.eHLS_App_Phrase_46;
		case BLEToyAudioPhrase.eP746:
			return BLEToyHLSequence.eHLS_App_Phrase_47;
		case BLEToyAudioPhrase.eP747:
			return BLEToyHLSequence.eHLS_App_Phrase_48;
		case BLEToyAudioPhrase.eP748:
			return BLEToyHLSequence.eHLS_App_Phrase_49;
		case BLEToyAudioPhrase.eP749:
			return BLEToyHLSequence.eHLS_App_Phrase_50;
		case BLEToyAudioPhrase.eP750:
			return BLEToyHLSequence.eHLS_App_Phrase_51;
		case BLEToyAudioPhrase.eP751:
			return BLEToyHLSequence.eHLS_App_Phrase_52;
		case BLEToyAudioPhrase.eP752:
			return BLEToyHLSequence.eHLS_App_Phrase_53;
		case BLEToyAudioPhrase.eP753:
			return BLEToyHLSequence.eHLS_App_Phrase_54;
		case BLEToyAudioPhrase.eP754:
			return BLEToyHLSequence.eHLS_App_Phrase_55;
		case BLEToyAudioPhrase.eP755:
			return BLEToyHLSequence.eHLS_App_Phrase_56;
		case BLEToyAudioPhrase.eP756:
			return BLEToyHLSequence.eHLS_App_Phrase_57;
		case BLEToyAudioPhrase.eP757:
			return BLEToyHLSequence.eHLS_App_Phrase_58;
		case BLEToyAudioPhrase.eP758:
			return BLEToyHLSequence.eHLS_App_Phrase_59;
		case BLEToyAudioPhrase.eP759:
			return BLEToyHLSequence.eHLS_App_Phrase_60;
		case BLEToyAudioPhrase.eP760:
			return BLEToyHLSequence.eHLS_App_Phrase_61;
		case BLEToyAudioPhrase.eP761:
			return BLEToyHLSequence.eHLS_App_Phrase_62;
		case BLEToyAudioPhrase.eP762:
			return BLEToyHLSequence.eHLS_App_Phrase_63;
		case BLEToyAudioPhrase.eP763:
			return BLEToyHLSequence.eHLS_App_Phrase_64;
		case BLEToyAudioPhrase.eP764:
			return BLEToyHLSequence.eHLS_App_Phrase_65;
		case BLEToyAudioPhrase.eP765:
			return BLEToyHLSequence.eHLS_App_Phrase_66;
		case BLEToyAudioPhrase.eP766:
			return BLEToyHLSequence.eHLS_App_Phrase_67;
		case BLEToyAudioPhrase.eP767:
			return BLEToyHLSequence.eHLS_App_Phrase_68;
		case BLEToyAudioPhrase.eP768:
			return BLEToyHLSequence.eHLS_App_Phrase_69;
		case BLEToyAudioPhrase.eP769:
			return BLEToyHLSequence.eHLS_App_Phrase_70;
		case BLEToyAudioPhrase.eP770:
			return BLEToyHLSequence.eHLS_App_Phrase_71;
		case BLEToyAudioPhrase.eP771:
			return BLEToyHLSequence.eHLS_App_Phrase_72;
		case BLEToyAudioPhrase.eP772:
			return BLEToyHLSequence.eHLS_App_Phrase_73;
		case BLEToyAudioPhrase.eP773:
			return BLEToyHLSequence.eHLS_App_Phrase_74;
		case BLEToyAudioPhrase.eP774:
			return BLEToyHLSequence.eHLS_App_Phrase_75;
		case BLEToyAudioPhrase.eP775:
			return BLEToyHLSequence.eHLS_App_Phrase_76;
		case BLEToyAudioPhrase.eP776:
			return BLEToyHLSequence.eHLS_App_Phrase_77;
		case BLEToyAudioPhrase.eP777:
			return BLEToyHLSequence.eHLS_App_Phrase_78;
		case BLEToyAudioPhrase.eP778:
			return BLEToyHLSequence.eHLS_App_Phrase_79;
		case BLEToyAudioPhrase.eP779:
			return BLEToyHLSequence.eHLS_App_Phrase_80;
		case BLEToyAudioPhrase.eP780:
			return BLEToyHLSequence.eHLS_App_Phrase_81;
		case BLEToyAudioPhrase.eP781:
			return BLEToyHLSequence.eHLS_App_Phrase_82;
		case BLEToyAudioPhrase.eP782:
			return BLEToyHLSequence.eHLS_App_Phrase_83;
		case BLEToyAudioPhrase.eP783:
			return BLEToyHLSequence.eHLS_App_Phrase_84;
		case BLEToyAudioPhrase.eP784:
			return BLEToyHLSequence.eHLS_App_Phrase_85;
		case BLEToyAudioPhrase.eP785:
			return BLEToyHLSequence.eHLS_App_Phrase_86;
		case BLEToyAudioPhrase.eP786:
			return BLEToyHLSequence.eHLS_App_Phrase_87;
		case BLEToyAudioPhrase.eP787:
			return BLEToyHLSequence.eHLS_App_Phrase_88;
		case BLEToyAudioPhrase.eP788:
			return BLEToyHLSequence.eHLS_App_Phrase_89;
		case BLEToyAudioPhrase.eP789:
			return BLEToyHLSequence.eHLS_App_Phrase_90;
		case BLEToyAudioPhrase.eP790:
			return BLEToyHLSequence.eHLS_App_Phrase_91;
		case BLEToyAudioPhrase.eP791:
			return BLEToyHLSequence.eHLS_App_Phrase_92;
		case BLEToyAudioPhrase.eP792:
			return BLEToyHLSequence.eHLS_App_Phrase_93;
		case BLEToyAudioPhrase.eP793:
			return BLEToyHLSequence.eHLS_App_Phrase_94;
		case BLEToyAudioPhrase.eP794:
			return BLEToyHLSequence.eHLS_App_Phrase_95;
		case BLEToyAudioPhrase.eP795:
			return BLEToyHLSequence.eHLS_App_Phrase_96;
		case BLEToyAudioPhrase.eP796:
			return BLEToyHLSequence.eHLS_App_Phrase_97;
		case BLEToyAudioPhrase.eP797:
			return BLEToyHLSequence.eHLS_App_Phrase_98;
		case BLEToyAudioPhrase.eP798:
			return BLEToyHLSequence.eHLS_App_Phrase_99;
		case BLEToyAudioPhrase.eP799:
			return BLEToyHLSequence.eHLS_App_Phrase_100;
		case BLEToyAudioPhrase.eP800:
			return BLEToyHLSequence.eHLS_App_Phrase_101;
		case BLEToyAudioPhrase.eP801:
			return BLEToyHLSequence.eHLS_App_Phrase_102;
		case BLEToyAudioPhrase.eP802:
			return BLEToyHLSequence.eHLS_App_Phrase_103;
		case BLEToyAudioPhrase.eP073:
			return BLEToyHLSequence.eHLS_DanceName_1;
		case BLEToyAudioPhrase.eP074:
			return BLEToyHLSequence.eHLS_DanceName_2;
		case BLEToyAudioPhrase.eP076:
			return BLEToyHLSequence.eHLS_DanceName_4;
		case BLEToyAudioPhrase.eP077:
			return BLEToyHLSequence.eHLS_DanceName_5;
		case BLEToyAudioPhrase.eP078:
			return BLEToyHLSequence.eHLS_DanceName_6;
		case BLEToyAudioPhrase.eP079:
			return BLEToyHLSequence.eHLS_DanceName_7;
		case BLEToyAudioPhrase.eP080:
			return BLEToyHLSequence.eHLS_DanceName_8;
		case BLEToyAudioPhrase.eP081:
			return BLEToyHLSequence.eHLS_DanceName_9;
		case BLEToyAudioPhrase.eP082:
			return BLEToyHLSequence.eHLS_DanceName_10;
		case BLEToyAudioPhrase.eP083:
			return BLEToyHLSequence.eHLS_DanceName_11_ALT;
		}
		return BLEToyHLSequence.eHLS_Wake_1;
	}

	public static BLEToyAudioPhrase PhraseForSequence(BLEToyHLSequence sequence)
	{
		switch (sequence)
		{
		case BLEToyHLSequence.eHLS_Wake_1:
			return BLEToyAudioPhrase.eP001;
		case BLEToyHLSequence.eHLS_Wake_2:
			return BLEToyAudioPhrase.eP002;
		case BLEToyHLSequence.eHLS_Wake_4:
			return BLEToyAudioPhrase.eP004;
		case BLEToyHLSequence.eHLS_Wake_5:
			return BLEToyAudioPhrase.eP005;
		case BLEToyHLSequence.eHLS_IdlePhrase_2:
			return BLEToyAudioPhrase.eP008;
		case BLEToyHLSequence.eHLS_IdlePhrase_3:
			return BLEToyAudioPhrase.eP009;
		case BLEToyHLSequence.eHLS_IdlePhrase_5:
			return BLEToyAudioPhrase.eP011;
		case BLEToyHLSequence.eHLS_IdlePhrase_6:
			return BLEToyAudioPhrase.eP012;
		case BLEToyHLSequence.eHLS_IdlePhrase_7:
			return BLEToyAudioPhrase.eP013;
		case BLEToyHLSequence.eHLS_IdlePhrase_8:
			return BLEToyAudioPhrase.eP014;
		case BLEToyHLSequence.eHLS_IdlePhrase_9:
			return BLEToyAudioPhrase.eP015;
		case BLEToyHLSequence.eHLS_IdlePhrase_10:
			return BLEToyAudioPhrase.eP016;
		case BLEToyHLSequence.eHLS_IdlePhrase_12:
			return BLEToyAudioPhrase.eP018;
		case BLEToyHLSequence.eHLS_IdlePhrase_13:
			return BLEToyAudioPhrase.eP019;
		case BLEToyHLSequence.eHLS_IdlePhrase_14:
			return BLEToyAudioPhrase.eP020;
		case BLEToyHLSequence.eHLS_IdlePhrase_15:
			return BLEToyAudioPhrase.eP021;
		case BLEToyHLSequence.eHLS_IdlePhrase_16:
			return BLEToyAudioPhrase.eP022;
		case BLEToyHLSequence.eHLS_IdlePhrase_17:
			return BLEToyAudioPhrase.eP023;
		case BLEToyHLSequence.eHLS_IdlePhrase_18:
			return BLEToyAudioPhrase.eP024;
		case BLEToyHLSequence.eHLS_IdlePhrase_19:
			return BLEToyAudioPhrase.eP025;
		case BLEToyHLSequence.eHLS_IdlePhrase_20:
			return BLEToyAudioPhrase.eP026;
		case BLEToyHLSequence.eHLS_IdlePhrase_22:
			return BLEToyAudioPhrase.eP028;
		case BLEToyHLSequence.eHLS_IdlePhrase_23:
			return BLEToyAudioPhrase.eP029;
		case BLEToyHLSequence.eHLS_IdlePhrase_27:
			return BLEToyAudioPhrase.eP006;
		case BLEToyHLSequence.eHLS_IdleInstruct_1:
			return BLEToyAudioPhrase.eP031;
		case BLEToyHLSequence.eHLS_IdleInstruct_2:
			return BLEToyAudioPhrase.eP032;
		case BLEToyHLSequence.eHLS_IdleInstruct_4:
			return BLEToyAudioPhrase.eP338;
		case BLEToyHLSequence.eHLS_IdleInstruct_6:
			return BLEToyAudioPhrase.eP340;
		case BLEToyHLSequence.eHLS_IdleInstruct_7:
			return BLEToyAudioPhrase.eP341;
		case BLEToyHLSequence.eHLS_IdleInstruct_9:
			return BLEToyAudioPhrase.eP339b;
		case BLEToyHLSequence.eHLS_Sleep_1:
			return BLEToyAudioPhrase.eP037;
		case BLEToyHLSequence.eHLS_Sleep_2:
			return BLEToyAudioPhrase.eP038;
		case BLEToyHLSequence.eHLS_Sleep_3:
			return BLEToyAudioPhrase.eP039;
		case BLEToyHLSequence.eHLS_Sleep_4:
			return BLEToyAudioPhrase.eP040;
		case BLEToyHLSequence.eHLS_Sleep_5:
			return BLEToyAudioPhrase.eP041;
		case BLEToyHLSequence.eHLS_Sleep_6:
			return BLEToyAudioPhrase.eP042;
		case BLEToyHLSequence.eHLS_Sleep_7:
			return BLEToyAudioPhrase.eP043;
		case BLEToyHLSequence.eHLS_ConnectStart_1:
			return BLEToyAudioPhrase.eP060;
		case BLEToyHLSequence.eHLS_ConnectStart_2:
			return BLEToyAudioPhrase.eP061;
		case BLEToyHLSequence.eHLS_ConnectStart_3:
			return BLEToyAudioPhrase.eP062;
		case BLEToyHLSequence.eHLS_ConnectStart_4:
			return BLEToyAudioPhrase.eP063;
		case BLEToyHLSequence.eHLS_ConnectStart_5:
			return BLEToyAudioPhrase.eP064;
		case BLEToyHLSequence.eHLS_DanceIntro_1:
			return BLEToyAudioPhrase.eP070;
		case BLEToyHLSequence.eHLS_DanceIntro_2:
			return BLEToyAudioPhrase.eP071;
		case BLEToyHLSequence.eHLS_DanceIntro_3:
			return BLEToyAudioPhrase.eP072;
		case BLEToyHLSequence.eHLS_DanceName_1:
			return BLEToyAudioPhrase.eP073;
		case BLEToyHLSequence.eHLS_DanceName_2:
			return BLEToyAudioPhrase.eP074;
		case BLEToyHLSequence.eHLS_DanceName_4:
			return BLEToyAudioPhrase.eP076;
		case BLEToyHLSequence.eHLS_DanceName_5:
			return BLEToyAudioPhrase.eP077;
		case BLEToyHLSequence.eHLS_DanceName_6:
			return BLEToyAudioPhrase.eP078;
		case BLEToyHLSequence.eHLS_DanceName_7:
			return BLEToyAudioPhrase.eP079;
		case BLEToyHLSequence.eHLS_DanceName_8:
			return BLEToyAudioPhrase.eP080;
		case BLEToyHLSequence.eHLS_DanceName_9:
			return BLEToyAudioPhrase.eP081;
		case BLEToyHLSequence.eHLS_DanceName_10:
			return BLEToyAudioPhrase.eP082;
		case BLEToyHLSequence.eHLS_DanceName_11_ALT:
			return BLEToyAudioPhrase.eP083;
		case BLEToyHLSequence.eHLS_DanceInstruct_1:
			return BLEToyAudioPhrase.eP084;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First:
			return BLEToyAudioPhrase.eP085;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final:
			return BLEToyAudioPhrase.eP086;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then:
			return BLEToyAudioPhrase.eP087;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Like:
			return BLEToyAudioPhrase.eP088;
		case BLEToyHLSequence.eHLS_DanceInstruct_1_ALTA:
			return BLEToyAudioPhrase.eP089;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTA:
			return BLEToyAudioPhrase.eP090;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTA:
			return BLEToyAudioPhrase.eP091;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTA:
			return BLEToyAudioPhrase.eP092;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Like_ALTA:
			return BLEToyAudioPhrase.eP093;
		case BLEToyHLSequence.eHLS_DanceInstruct_1_ALTB:
			return BLEToyAudioPhrase.eP094;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTB:
			return BLEToyAudioPhrase.eP095;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTB:
			return BLEToyAudioPhrase.eP096;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTB:
			return BLEToyAudioPhrase.eP097;
		case BLEToyHLSequence.eHLS_DanceInstruct_2:
			return BLEToyAudioPhrase.eP098;
		case BLEToyHLSequence.eHLS_DanceInstruct_2First:
			return BLEToyAudioPhrase.eP099;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Final:
			return BLEToyAudioPhrase.eP100;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Then:
			return BLEToyAudioPhrase.eP101;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Like:
			return BLEToyAudioPhrase.eP102;
		case BLEToyHLSequence.eHLS_DanceInstruct_3:
			return BLEToyAudioPhrase.eP103;
		case BLEToyHLSequence.eHLS_DanceInstruct_3First:
			return BLEToyAudioPhrase.eP104;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Final:
			return BLEToyAudioPhrase.eP105;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Then:
			return BLEToyAudioPhrase.eP106;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Like:
			return BLEToyAudioPhrase.eP107;
		case BLEToyHLSequence.eHLS_DanceInstruct_4:
			return BLEToyAudioPhrase.eP108;
		case BLEToyHLSequence.eHLS_DanceInstruct_4First:
			return BLEToyAudioPhrase.eP109;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Final:
			return BLEToyAudioPhrase.eP110;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Next:
			return BLEToyAudioPhrase.eP111;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Like:
			return BLEToyAudioPhrase.eP112;
		case BLEToyHLSequence.eHLS_DanceInstruct_4_ALT:
			return BLEToyAudioPhrase.eP113;
		case BLEToyHLSequence.eHLS_DanceInstruct_4First_ALT:
			return BLEToyAudioPhrase.eP114;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Final_ALT:
			return BLEToyAudioPhrase.eP115;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Next_ALT:
			return BLEToyAudioPhrase.eP116;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Like_ALT:
			return BLEToyAudioPhrase.eP117;
		case BLEToyHLSequence.eHLS_DanceInstruct_5:
			return BLEToyAudioPhrase.eP118;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First:
			return BLEToyAudioPhrase.eP119;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final:
			return BLEToyAudioPhrase.eP120;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then:
			return BLEToyAudioPhrase.eP121;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like:
			return BLEToyAudioPhrase.eP122;
		case BLEToyHLSequence.eHLS_DanceInstruct_5_ALTA:
			return BLEToyAudioPhrase.eP123;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTA:
			return BLEToyAudioPhrase.eP124;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTA:
			return BLEToyAudioPhrase.eP125;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTA:
			return BLEToyAudioPhrase.eP126;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTA:
			return BLEToyAudioPhrase.eP127;
		case BLEToyHLSequence.eHLS_DanceInstruct_5_ALTB:
			return BLEToyAudioPhrase.eP128;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTB:
			return BLEToyAudioPhrase.eP129;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTB:
			return BLEToyAudioPhrase.eP130;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTB:
			return BLEToyAudioPhrase.eP131;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTB:
			return BLEToyAudioPhrase.eP132;
		case BLEToyHLSequence.eHLS_DanceInstruct_6:
			return BLEToyAudioPhrase.eP133;
		case BLEToyHLSequence.eHLS_DanceInstruct_6First:
			return BLEToyAudioPhrase.eP134;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Final:
			return BLEToyAudioPhrase.eP135;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Next:
			return BLEToyAudioPhrase.eP136;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Like:
			return BLEToyAudioPhrase.eP137;
		case BLEToyHLSequence.eHLS_DanceInstruct_6_ALT:
			return BLEToyAudioPhrase.eP138;
		case BLEToyHLSequence.eHLS_DanceInstruct_6First_ALT:
			return BLEToyAudioPhrase.eP139;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Final_ALT:
			return BLEToyAudioPhrase.eP140;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Next_ALT:
			return BLEToyAudioPhrase.eP141;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Like_ALT:
			return BLEToyAudioPhrase.eP142;
		case BLEToyHLSequence.eHLS_DanceInstruct_7:
			return BLEToyAudioPhrase.eP143;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First:
			return BLEToyAudioPhrase.eP144;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final:
			return BLEToyAudioPhrase.eP145;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then:
			return BLEToyAudioPhrase.eP146;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like:
			return BLEToyAudioPhrase.eP147;
		case BLEToyHLSequence.eHLS_DanceInstruct_7_ALTA:
			return BLEToyAudioPhrase.eP148;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTA:
			return BLEToyAudioPhrase.eP149;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTA:
			return BLEToyAudioPhrase.eP150;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTA:
			return BLEToyAudioPhrase.eP151;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTA:
			return BLEToyAudioPhrase.eP152;
		case BLEToyHLSequence.eHLS_DanceInstruct_7_ALTB:
			return BLEToyAudioPhrase.eP153;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTB:
			return BLEToyAudioPhrase.eP154;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTB:
			return BLEToyAudioPhrase.eP155;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTB:
			return BLEToyAudioPhrase.eP156;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTB:
			return BLEToyAudioPhrase.eP157;
		case BLEToyHLSequence.eHLS_DanceInstruct_8:
			return BLEToyAudioPhrase.eP158;
		case BLEToyHLSequence.eHLS_DanceInstruct_8First:
			return BLEToyAudioPhrase.eP159;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Final:
			return BLEToyAudioPhrase.eP160;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Next:
			return BLEToyAudioPhrase.eP161;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Like:
			return BLEToyAudioPhrase.eP162;
		case BLEToyHLSequence.eHLS_DanceInstruct_9:
			return BLEToyAudioPhrase.eP163;
		case BLEToyHLSequence.eHLS_DanceInstruct_9First:
			return BLEToyAudioPhrase.eP164;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Final:
			return BLEToyAudioPhrase.eP165;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Then:
			return BLEToyAudioPhrase.eP166;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Like:
			return BLEToyAudioPhrase.eP167;
		case BLEToyHLSequence.eHLS_DanceInstruct_10:
			return BLEToyAudioPhrase.eP168;
		case BLEToyHLSequence.eHLS_DanceInstruct_10First:
			return BLEToyAudioPhrase.eP169;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Final:
			return BLEToyAudioPhrase.eP170;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Next:
			return BLEToyAudioPhrase.eP171;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Like:
			return BLEToyAudioPhrase.eP172;
		case BLEToyHLSequence.eHLS_DanceInstruct_10_ALT:
			return BLEToyAudioPhrase.eP173;
		case BLEToyHLSequence.eHLS_DanceInstruct_10First_ALT:
			return BLEToyAudioPhrase.eP174;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Final_ALT:
			return BLEToyAudioPhrase.eP175;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Next_ALT:
			return BLEToyAudioPhrase.eP176;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Next_ALTb:
			return BLEToyAudioPhrase.eP176b;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Like_ALT:
			return BLEToyAudioPhrase.eP177;
		case BLEToyHLSequence.eHLS_DanceInstruct_11:
			return BLEToyAudioPhrase.eP178;
		case BLEToyHLSequence.eHLS_DanceInstruct_11First:
			return BLEToyAudioPhrase.eP179;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Final:
			return BLEToyAudioPhrase.eP180;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Then:
			return BLEToyAudioPhrase.eP181;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Like:
			return BLEToyAudioPhrase.eP182;
		case BLEToyHLSequence.eHLS_DanceInstruct_Spin_1:
			return BLEToyAudioPhrase.eP183;
		case BLEToyHLSequence.eHLS_DanceInstruct_Spin_1_ALT:
			return BLEToyAudioPhrase.eP184;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1:
			return BLEToyAudioPhrase.eP185;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1:
			return BLEToyAudioPhrase.eP186;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1:
			return BLEToyAudioPhrase.eP187;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1:
			return BLEToyAudioPhrase.eP188;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1:
			return BLEToyAudioPhrase.eP189;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTA:
			return BLEToyAudioPhrase.eP190;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1B:
			return BLEToyAudioPhrase.eP191;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1B:
			return BLEToyAudioPhrase.eP192;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTA:
			return BLEToyAudioPhrase.eP193;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTA:
			return BLEToyAudioPhrase.eP194;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTB:
			return BLEToyAudioPhrase.eP195;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1C:
			return BLEToyAudioPhrase.eP196;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1C:
			return BLEToyAudioPhrase.eP197;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTB:
			return BLEToyAudioPhrase.eP198;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTB:
			return BLEToyAudioPhrase.eP199;
		case BLEToyHLSequence.eHLS_DanceInstruct_SpinAgain_1:
			return BLEToyAudioPhrase.eP200;
		case BLEToyHLSequence.eHLS_DanceInstruct_SpinOther_1:
			return BLEToyAudioPhrase.eP201;
		case BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1:
			return BLEToyAudioPhrase.eP202;
		case BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1_ALT:
			return BLEToyAudioPhrase.eP203;
		case BLEToyHLSequence.eHLS_DanceInstruct_Fwd_1:
			return BLEToyAudioPhrase.eP204;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdFirst_1:
			return BLEToyAudioPhrase.eP205;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdFinal_1:
			return BLEToyAudioPhrase.eP206;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdNow_1:
			return BLEToyAudioPhrase.eP207;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdThen_1:
			return BLEToyAudioPhrase.eP208;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdThen_1b:
			return BLEToyAudioPhrase.eP208b;
		case BLEToyHLSequence.eHLS_DanceInstruct_Back_1:
			return BLEToyAudioPhrase.eP209;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackFirst_1:
			return BLEToyAudioPhrase.eP210;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackFinal_1:
			return BLEToyAudioPhrase.eP211;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackNow_1:
			return BLEToyAudioPhrase.eP212;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackThen_1:
			return BLEToyAudioPhrase.eP213;
		case BLEToyHLSequence.eHLS_DanceInstruct_Turn_1:
			return BLEToyAudioPhrase.eP214;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1:
			return BLEToyAudioPhrase.eP215;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1:
			return BLEToyAudioPhrase.eP216;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1:
			return BLEToyAudioPhrase.eP217;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1:
			return BLEToyAudioPhrase.eP218;
		case BLEToyHLSequence.eHLS_DanceInstruct_Turn_1_ALT:
			return BLEToyAudioPhrase.eP219;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1_ALT:
			return BLEToyAudioPhrase.eP220;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1_ALT:
			return BLEToyAudioPhrase.eP221;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1_ALT:
			return BLEToyAudioPhrase.eP222;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1_ALT:
			return BLEToyAudioPhrase.eP223;
		case BLEToyHLSequence.eHLS_DanceInstruct_FaceFwd_1:
			return BLEToyAudioPhrase.eP224;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1:
			return BLEToyAudioPhrase.eP225;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1_ALT:
			return BLEToyAudioPhrase.eP226;
		case BLEToyHLSequence.eHLS_DanceInstruct_Arms_1:
			return BLEToyAudioPhrase.eP227;
		case BLEToyHLSequence.eHLS_DanceInstruct_Arms_1b:
			return BLEToyAudioPhrase.eP227b;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsFirst_1:
			return BLEToyAudioPhrase.eP228;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsNow_1:
			return BLEToyAudioPhrase.eP229;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsThen_1:
			return BLEToyAudioPhrase.eP230;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsFinal_1:
			return BLEToyAudioPhrase.eP231;
		case BLEToyHLSequence.eHLS_DanceInstruct_Move_1:
			return BLEToyAudioPhrase.eP232;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveFirst_1:
			return BLEToyAudioPhrase.eP233;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveNow_1:
			return BLEToyAudioPhrase.eP234;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveThen_1:
			return BLEToyAudioPhrase.eP235;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveFinal_1:
			return BLEToyAudioPhrase.eP236;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_1:
			return BLEToyAudioPhrase.eP237;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_2:
			return BLEToyAudioPhrase.eP238;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_3:
			return BLEToyAudioPhrase.eP239;
		case BLEToyHLSequence.eHLS_DanceInstruct_Generic_1:
			return BLEToyAudioPhrase.eP240;
		case BLEToyHLSequence.eHLS_DanceInstruct_Generic_2:
			return BLEToyAudioPhrase.eP241;
		case BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1:
			return BLEToyAudioPhrase.eP242;
		case BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1_ALT:
			return BLEToyAudioPhrase.eP243;
		case BLEToyHLSequence.eHLS_DanceInstruct_Connect_1:
			return BLEToyAudioPhrase.eP244;
		case BLEToyHLSequence.eHLS_DanceInstruct_Connect_1b:
			return BLEToyAudioPhrase.eP244b;
		case BLEToyHLSequence.eHLS_DanceInstruct_Connect_1c:
			return BLEToyAudioPhrase.eP244c;
		case BLEToyHLSequence.eHLS_Encourage_1:
			return BLEToyAudioPhrase.eP245;
		case BLEToyHLSequence.eHLS_Encourage_2:
			return BLEToyAudioPhrase.eP246;
		case BLEToyHLSequence.eHLS_Encourage_3:
			return BLEToyAudioPhrase.eP247;
		case BLEToyHLSequence.eHLS_Encourage_4:
			return BLEToyAudioPhrase.eP248;
		case BLEToyHLSequence.eHLS_Encourage_5:
			return BLEToyAudioPhrase.eP249;
		case BLEToyHLSequence.eHLS_Encourage_6:
			return BLEToyAudioPhrase.eP250;
		case BLEToyHLSequence.eHLS_Encourage_7:
			return BLEToyAudioPhrase.eP251;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_1:
			return BLEToyAudioPhrase.eP252;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_2:
			return BLEToyAudioPhrase.eP253;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_3:
			return BLEToyAudioPhrase.eP254;
		case BLEToyHLSequence.eHLS_LiftPhrase_1:
			return BLEToyAudioPhrase.eP270;
		case BLEToyHLSequence.eHLS_LiftPhrase_2:
			return BLEToyAudioPhrase.eP271;
		case BLEToyHLSequence.eHLS_LiftPhrase_4:
			return BLEToyAudioPhrase.eP273;
		case BLEToyHLSequence.eHLS_LiftPhrase_5:
			return BLEToyAudioPhrase.eP274;
		case BLEToyHLSequence.eHLS_DanceTogether_1:
			return BLEToyAudioPhrase.eP260;
		case BLEToyHLSequence.eHLS_DanceTogether_2:
			return BLEToyAudioPhrase.eP261;
		case BLEToyHLSequence.eHLS_DanceTogether_3:
			return BLEToyAudioPhrase.eP262;
		case BLEToyHLSequence.eHLS_DanceTogether_4:
			return BLEToyAudioPhrase.eP263;
		case BLEToyHLSequence.eHLS_DanceTogether_5:
			return BLEToyAudioPhrase.eP264;
		case BLEToyHLSequence.eHLS_DanceTogether_6:
			return BLEToyAudioPhrase.eP265;
		case BLEToyHLSequence.eHLS_DanceTogether_7:
			return BLEToyAudioPhrase.eP266;
		case BLEToyHLSequence.eHLS_DanceTogether_8:
			return BLEToyAudioPhrase.eP267;
		case BLEToyHLSequence.eHLS_DanceBreak_1:
			return BLEToyAudioPhrase.eP268;
		case BLEToyHLSequence.eHLS_DanceBreak_2:
			return BLEToyAudioPhrase.eP269;
		case BLEToyHLSequence.eHLS_AppConnect_1:
			return BLEToyAudioPhrase.eP276;
		case BLEToyHLSequence.eHLS_ButtonPress_1:
			return BLEToyAudioPhrase.eP277;
		case BLEToyHLSequence.eHLS_SleepButtonPress_1:
			return BLEToyAudioPhrase.eP278;
		case BLEToyHLSequence.eHLS_DanceRoutine_1:
			return BLEToyAudioPhrase.eP279;
		case BLEToyHLSequence.eHLS_DanceRoutine_2:
			return BLEToyAudioPhrase.eP280;
		case BLEToyHLSequence.eHLS_DanceRoutine_3:
			return BLEToyAudioPhrase.eP281;
		case BLEToyHLSequence.eHLS_DanceRoutine_4:
			return BLEToyAudioPhrase.eP282;
		case BLEToyHLSequence.eHLS_DanceRoutine_5:
			return BLEToyAudioPhrase.eP283;
		case BLEToyHLSequence.eHLS_DanceRoutine_6:
			return BLEToyAudioPhrase.eP284;
		case BLEToyHLSequence.eHLS_DanceRoutine_7:
			return BLEToyAudioPhrase.eP285;
		case BLEToyHLSequence.eHLS_DanceRoutine_8:
			return BLEToyAudioPhrase.eP286;
		case BLEToyHLSequence.eHLS_DanceRoutine_9:
			return BLEToyAudioPhrase.eP287;
		case BLEToyHLSequence.eHLS_DanceRoutine_10:
			return BLEToyAudioPhrase.eP288;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_1:
			return BLEToyAudioPhrase.eP238;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_2:
			return BLEToyAudioPhrase.eP313;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_3:
			return BLEToyAudioPhrase.eP314;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_4:
			return BLEToyAudioPhrase.eP315;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_6:
			return BLEToyAudioPhrase.eP317;
		case BLEToyHLSequence.eHLS_ShortInstruct_1:
			return BLEToyAudioPhrase.eP318;
		case BLEToyHLSequence.eHLS_ShortInstruct_1_ALTA:
			return BLEToyAudioPhrase.eP319;
		case BLEToyHLSequence.eHLS_ShortInstruct_2:
			return BLEToyAudioPhrase.eP320;
		case BLEToyHLSequence.eHLS_ShortInstruct_3:
			return BLEToyAudioPhrase.eP321;
		case BLEToyHLSequence.eHLS_ShortInstruct_4:
			return BLEToyAudioPhrase.eP322;
		case BLEToyHLSequence.eHLS_ShortInstruct_4_ALT:
			return BLEToyAudioPhrase.eP323;
		case BLEToyHLSequence.eHLS_ShortInstruct_5:
			return BLEToyAudioPhrase.eP324;
		case BLEToyHLSequence.eHLS_ShortInstruct_6:
			return BLEToyAudioPhrase.eP325;
		case BLEToyHLSequence.eHLS_ShortInstruct_7:
			return BLEToyAudioPhrase.eP326;
		case BLEToyHLSequence.eHLS_ShortInstruct_7_ALTB:
			return BLEToyAudioPhrase.eP153;
		case BLEToyHLSequence.eHLS_ShortInstruct_8:
			return BLEToyAudioPhrase.eP327;
		case BLEToyHLSequence.eHLS_ShortInstruct_9:
			return BLEToyAudioPhrase.eP328;
		case BLEToyHLSequence.eHLS_ShortInstruct_10_ALT:
			return BLEToyAudioPhrase.eP329;
		case BLEToyHLSequence.eHLS_ShortInstruct_Spin_1:
			return BLEToyAudioPhrase.eP330;
		case BLEToyHLSequence.eHLS_ShortInstruct_Spin_1_ALT:
			return BLEToyAudioPhrase.eP331;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1:
			return BLEToyAudioPhrase.eP185;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1_ALTA:
			return BLEToyAudioPhrase.eP190;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1_ALTB:
			return BLEToyAudioPhrase.eP195;
		case BLEToyHLSequence.eHLS_ShortInstruct_SpinAgain_1:
			return BLEToyAudioPhrase.eP332;
		case BLEToyHLSequence.eHLS_ShortInstruct_SpinOther_1:
			return BLEToyAudioPhrase.eP333;
		case BLEToyHLSequence.eHLS_ShortInstruct_Curtsy_1:
			return BLEToyAudioPhrase.eP202;
		case BLEToyHLSequence.eHLS_ShortInstruct_Curtsy_1_ALT:
			return BLEToyAudioPhrase.eP203;
		case BLEToyHLSequence.eHLS_ShortInstruct_Fwd_1:
			return BLEToyAudioPhrase.eP204;
		case BLEToyHLSequence.eHLS_ShortInstruct_Back_1:
			return BLEToyAudioPhrase.eP209;
		case BLEToyHLSequence.eHLS_ShortInstruct_Turn_1:
			return BLEToyAudioPhrase.eP214;
		case BLEToyHLSequence.eHLS_ShortInstruct_Turn_1_ALT:
			return BLEToyAudioPhrase.eP219;
		case BLEToyHLSequence.eHLS_ShortInstruct_FaceFwd_1:
			return BLEToyAudioPhrase.eP334;
		case BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1:
			return BLEToyAudioPhrase.eP335;
		case BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1_ALT:
			return BLEToyAudioPhrase.eP336;
		case BLEToyHLSequence.eHLS_ShortInstruct_Move_1:
			return BLEToyAudioPhrase.eP337;
		case BLEToyHLSequence.eHLS_ShortInstruct_MoveThen_1:
			return BLEToyAudioPhrase.eP235;
		case BLEToyHLSequence.eHLS_ShortInstruct_Generic_2:
			return BLEToyAudioPhrase.eP241;
		case BLEToyHLSequence.eHLS_App_Phrase_1:
			return BLEToyAudioPhrase.eP700;
		case BLEToyHLSequence.eHLS_App_Phrase_2:
			return BLEToyAudioPhrase.eP701;
		case BLEToyHLSequence.eHLS_App_Phrase_3:
			return BLEToyAudioPhrase.eP702;
		case BLEToyHLSequence.eHLS_App_Phrase_4:
			return BLEToyAudioPhrase.eP703;
		case BLEToyHLSequence.eHLS_App_Phrase_5:
			return BLEToyAudioPhrase.eP704;
		case BLEToyHLSequence.eHLS_App_Phrase_6:
			return BLEToyAudioPhrase.eP705;
		case BLEToyHLSequence.eHLS_App_Phrase_7:
			return BLEToyAudioPhrase.eP706;
		case BLEToyHLSequence.eHLS_App_Phrase_8:
			return BLEToyAudioPhrase.eP707;
		case BLEToyHLSequence.eHLS_App_Phrase_9:
			return BLEToyAudioPhrase.eP708;
		case BLEToyHLSequence.eHLS_App_Phrase_10:
			return BLEToyAudioPhrase.eP709;
		case BLEToyHLSequence.eHLS_App_Phrase_11:
			return BLEToyAudioPhrase.eP710;
		case BLEToyHLSequence.eHLS_App_Phrase_12:
			return BLEToyAudioPhrase.eP711;
		case BLEToyHLSequence.eHLS_App_Phrase_13:
			return BLEToyAudioPhrase.eP712;
		case BLEToyHLSequence.eHLS_App_Phrase_14:
			return BLEToyAudioPhrase.eP713;
		case BLEToyHLSequence.eHLS_App_Phrase_15:
			return BLEToyAudioPhrase.eP714;
		case BLEToyHLSequence.eHLS_App_Phrase_16:
			return BLEToyAudioPhrase.eP715;
		case BLEToyHLSequence.eHLS_App_Phrase_17:
			return BLEToyAudioPhrase.eP716;
		case BLEToyHLSequence.eHLS_App_Phrase_18:
			return BLEToyAudioPhrase.eP717;
		case BLEToyHLSequence.eHLS_App_Phrase_19:
			return BLEToyAudioPhrase.eP718;
		case BLEToyHLSequence.eHLS_App_Phrase_20:
			return BLEToyAudioPhrase.eP719;
		case BLEToyHLSequence.eHLS_App_Phrase_21:
			return BLEToyAudioPhrase.eP720;
		case BLEToyHLSequence.eHLS_App_Phrase_22:
			return BLEToyAudioPhrase.eP721;
		case BLEToyHLSequence.eHLS_App_Phrase_23:
			return BLEToyAudioPhrase.eP722;
		case BLEToyHLSequence.eHLS_App_Phrase_24:
			return BLEToyAudioPhrase.eP723;
		case BLEToyHLSequence.eHLS_App_Phrase_25:
			return BLEToyAudioPhrase.eP724;
		case BLEToyHLSequence.eHLS_App_Phrase_26:
			return BLEToyAudioPhrase.eP725;
		case BLEToyHLSequence.eHLS_App_Phrase_27:
			return BLEToyAudioPhrase.eP726;
		case BLEToyHLSequence.eHLS_App_Phrase_28:
			return BLEToyAudioPhrase.eP727;
		case BLEToyHLSequence.eHLS_App_Phrase_29:
			return BLEToyAudioPhrase.eP728;
		case BLEToyHLSequence.eHLS_App_Phrase_30:
			return BLEToyAudioPhrase.eP729;
		case BLEToyHLSequence.eHLS_App_Phrase_31:
			return BLEToyAudioPhrase.eP730;
		case BLEToyHLSequence.eHLS_App_Phrase_32:
			return BLEToyAudioPhrase.eP731;
		case BLEToyHLSequence.eHLS_App_Phrase_33:
			return BLEToyAudioPhrase.eP732;
		case BLEToyHLSequence.eHLS_App_Phrase_34:
			return BLEToyAudioPhrase.eP733;
		case BLEToyHLSequence.eHLS_App_Phrase_34_alt1:
			return BLEToyAudioPhrase.eP733B;
		case BLEToyHLSequence.eHLS_App_Phrase_34_alt2:
			return BLEToyAudioPhrase.eP733C;
		case BLEToyHLSequence.eHLS_App_Phrase_35:
			return BLEToyAudioPhrase.eP734;
		case BLEToyHLSequence.eHLS_App_Phrase_36:
			return BLEToyAudioPhrase.eP735;
		case BLEToyHLSequence.eHLS_App_Phrase_37:
			return BLEToyAudioPhrase.eP736;
		case BLEToyHLSequence.eHLS_App_Phrase_38:
			return BLEToyAudioPhrase.eP737;
		case BLEToyHLSequence.eHLS_App_Phrase_39:
			return BLEToyAudioPhrase.eP738;
		case BLEToyHLSequence.eHLS_App_Phrase_40:
			return BLEToyAudioPhrase.eP739;
		case BLEToyHLSequence.eHLS_App_Phrase_41:
			return BLEToyAudioPhrase.eP740;
		case BLEToyHLSequence.eHLS_App_Phrase_42:
			return BLEToyAudioPhrase.eP741;
		case BLEToyHLSequence.eHLS_App_Phrase_43:
			return BLEToyAudioPhrase.eP742;
		case BLEToyHLSequence.eHLS_App_Phrase_44:
			return BLEToyAudioPhrase.eP743;
		case BLEToyHLSequence.eHLS_App_Phrase_45:
			return BLEToyAudioPhrase.eP744;
		case BLEToyHLSequence.eHLS_App_Phrase_46:
			return BLEToyAudioPhrase.eP745;
		case BLEToyHLSequence.eHLS_App_Phrase_47:
			return BLEToyAudioPhrase.eP746;
		case BLEToyHLSequence.eHLS_App_Phrase_48:
			return BLEToyAudioPhrase.eP747;
		case BLEToyHLSequence.eHLS_App_Phrase_49:
			return BLEToyAudioPhrase.eP748;
		case BLEToyHLSequence.eHLS_App_Phrase_50:
			return BLEToyAudioPhrase.eP749;
		case BLEToyHLSequence.eHLS_App_Phrase_51:
			return BLEToyAudioPhrase.eP750;
		case BLEToyHLSequence.eHLS_App_Phrase_52:
			return BLEToyAudioPhrase.eP751;
		case BLEToyHLSequence.eHLS_App_Phrase_53:
			return BLEToyAudioPhrase.eP752;
		case BLEToyHLSequence.eHLS_App_Phrase_54:
			return BLEToyAudioPhrase.eP753;
		case BLEToyHLSequence.eHLS_App_Phrase_55:
			return BLEToyAudioPhrase.eP754;
		case BLEToyHLSequence.eHLS_App_Phrase_56:
			return BLEToyAudioPhrase.eP755;
		case BLEToyHLSequence.eHLS_App_Phrase_57:
			return BLEToyAudioPhrase.eP756;
		case BLEToyHLSequence.eHLS_App_Phrase_58:
			return BLEToyAudioPhrase.eP757;
		case BLEToyHLSequence.eHLS_App_Phrase_59:
			return BLEToyAudioPhrase.eP758;
		case BLEToyHLSequence.eHLS_App_Phrase_60:
			return BLEToyAudioPhrase.eP759;
		case BLEToyHLSequence.eHLS_App_Phrase_61:
			return BLEToyAudioPhrase.eP760;
		case BLEToyHLSequence.eHLS_App_Phrase_62:
			return BLEToyAudioPhrase.eP761;
		case BLEToyHLSequence.eHLS_App_Phrase_63:
			return BLEToyAudioPhrase.eP762;
		case BLEToyHLSequence.eHLS_App_Phrase_64:
			return BLEToyAudioPhrase.eP763;
		case BLEToyHLSequence.eHLS_App_Phrase_65:
			return BLEToyAudioPhrase.eP764;
		case BLEToyHLSequence.eHLS_App_Phrase_66:
			return BLEToyAudioPhrase.eP765;
		case BLEToyHLSequence.eHLS_App_Phrase_67:
			return BLEToyAudioPhrase.eP766;
		case BLEToyHLSequence.eHLS_App_Phrase_68:
			return BLEToyAudioPhrase.eP767;
		case BLEToyHLSequence.eHLS_App_Phrase_69:
			return BLEToyAudioPhrase.eP768;
		case BLEToyHLSequence.eHLS_App_Phrase_70:
			return BLEToyAudioPhrase.eP769;
		case BLEToyHLSequence.eHLS_App_Phrase_71:
			return BLEToyAudioPhrase.eP770;
		case BLEToyHLSequence.eHLS_App_Phrase_72:
			return BLEToyAudioPhrase.eP771;
		case BLEToyHLSequence.eHLS_App_Phrase_73:
			return BLEToyAudioPhrase.eP772;
		case BLEToyHLSequence.eHLS_App_Phrase_74:
			return BLEToyAudioPhrase.eP773;
		case BLEToyHLSequence.eHLS_App_Phrase_75:
			return BLEToyAudioPhrase.eP774;
		case BLEToyHLSequence.eHLS_App_Phrase_76:
			return BLEToyAudioPhrase.eP775;
		case BLEToyHLSequence.eHLS_App_Phrase_77:
			return BLEToyAudioPhrase.eP776;
		case BLEToyHLSequence.eHLS_App_Phrase_78:
			return BLEToyAudioPhrase.eP777;
		case BLEToyHLSequence.eHLS_App_Phrase_79:
			return BLEToyAudioPhrase.eP778;
		case BLEToyHLSequence.eHLS_App_Phrase_80:
			return BLEToyAudioPhrase.eP779;
		case BLEToyHLSequence.eHLS_App_Phrase_81:
			return BLEToyAudioPhrase.eP780;
		case BLEToyHLSequence.eHLS_App_Phrase_82:
			return BLEToyAudioPhrase.eP781;
		case BLEToyHLSequence.eHLS_App_Phrase_83:
			return BLEToyAudioPhrase.eP782;
		case BLEToyHLSequence.eHLS_App_Phrase_84:
			return BLEToyAudioPhrase.eP783;
		case BLEToyHLSequence.eHLS_App_Phrase_85:
			return BLEToyAudioPhrase.eP784;
		case BLEToyHLSequence.eHLS_App_Phrase_86:
			return BLEToyAudioPhrase.eP785;
		case BLEToyHLSequence.eHLS_App_Phrase_87:
			return BLEToyAudioPhrase.eP786;
		case BLEToyHLSequence.eHLS_App_Phrase_88:
			return BLEToyAudioPhrase.eP787;
		case BLEToyHLSequence.eHLS_App_Phrase_89:
			return BLEToyAudioPhrase.eP788;
		case BLEToyHLSequence.eHLS_App_Phrase_90:
			return BLEToyAudioPhrase.eP789;
		case BLEToyHLSequence.eHLS_App_Phrase_91:
			return BLEToyAudioPhrase.eP790;
		case BLEToyHLSequence.eHLS_App_Phrase_92:
			return BLEToyAudioPhrase.eP791;
		case BLEToyHLSequence.eHLS_App_Phrase_93:
			return BLEToyAudioPhrase.eP792;
		case BLEToyHLSequence.eHLS_App_Phrase_94:
			return BLEToyAudioPhrase.eP793;
		case BLEToyHLSequence.eHLS_App_Phrase_95:
			return BLEToyAudioPhrase.eP794;
		case BLEToyHLSequence.eHLS_App_Phrase_96:
			return BLEToyAudioPhrase.eP795;
		case BLEToyHLSequence.eHLS_App_Phrase_97:
			return BLEToyAudioPhrase.eP796;
		case BLEToyHLSequence.eHLS_App_Phrase_98:
			return BLEToyAudioPhrase.eP797;
		case BLEToyHLSequence.eHLS_App_Phrase_99:
			return BLEToyAudioPhrase.eP798;
		case BLEToyHLSequence.eHLS_App_Phrase_100:
			return BLEToyAudioPhrase.eP799;
		case BLEToyHLSequence.eHLS_App_Phrase_101:
			return BLEToyAudioPhrase.eP800;
		case BLEToyHLSequence.eHLS_App_Phrase_102:
			return BLEToyAudioPhrase.eP801;
		case BLEToyHLSequence.eHLS_App_Phrase_103:
			return BLEToyAudioPhrase.eP802;
		case BLEToyHLSequence.eHLS_App_alt_1:
			return BLEToyAudioPhrase.eP003;
		case BLEToyHLSequence.eHLS_App_alt_2:
			return BLEToyAudioPhrase.eP010;
		case BLEToyHLSequence.eHLS_App_alt_3:
			return BLEToyAudioPhrase.eP017;
		case BLEToyHLSequence.eHLS_App_alt_4:
			return BLEToyAudioPhrase.eP027;
		case BLEToyHLSequence.eHLS_App_alt_5:
			return BLEToyAudioPhrase.eP033;
		case BLEToyHLSequence.eHLS_App_alt_6:
			return BLEToyAudioPhrase.eP339;
		case BLEToyHLSequence.eHLS_App_alt_7:
			return BLEToyAudioPhrase.eP342;
		case BLEToyHLSequence.eHLS_App_alt_8:
			return BLEToyAudioPhrase.eP255;
		case BLEToyHLSequence.eHLS_App_alt_9:
			return BLEToyAudioPhrase.eP256;
		case BLEToyHLSequence.eHLS_App_alt_10:
			return BLEToyAudioPhrase.eP257;
		case BLEToyHLSequence.eHLS_App_alt_11:
			return BLEToyAudioPhrase.eP258;
		case BLEToyHLSequence.eHLS_App_alt_12:
			return BLEToyAudioPhrase.eP259;
		case BLEToyHLSequence.eHLS_App_alt_13:
			return BLEToyAudioPhrase.eP272;
		case BLEToyHLSequence.eHLS_App_alt_14:
			return BLEToyAudioPhrase.eP275;
		case BLEToyHLSequence.eHLS_App_alt_15:
			return BLEToyAudioPhrase.eP303;
		case BLEToyHLSequence.eHLS_App_alt_16:
			return BLEToyAudioPhrase.eP304;
		case BLEToyHLSequence.eHLS_App_alt_17:
			return BLEToyAudioPhrase.eP305;
		case BLEToyHLSequence.eHLS_App_alt_18:
			return BLEToyAudioPhrase.eP306;
		case BLEToyHLSequence.eHLS_App_alt_19:
			return BLEToyAudioPhrase.eP307;
		case BLEToyHLSequence.eHLS_App_alt_20:
			return BLEToyAudioPhrase.eP308;
		case BLEToyHLSequence.eHLS_App_alt_21:
			return BLEToyAudioPhrase.eP309;
		case BLEToyHLSequence.eHLS_App_alt_22:
			return BLEToyAudioPhrase.eP310;
		case BLEToyHLSequence.eHLS_App_alt_23:
			return BLEToyAudioPhrase.eP311;
		case BLEToyHLSequence.eHLS_App_alt_24:
			return BLEToyAudioPhrase.eP312;
		case BLEToyHLSequence.eHLS_App_alt_25:
			return BLEToyAudioPhrase.eP316;
		case BLEToyHLSequence.eHLS_App_alt_26:
			return BLEToyAudioPhrase.eP065;
		case BLEToyHLSequence.eHLS_App_alt_27:
			return BLEToyAudioPhrase.eP066;
		case BLEToyHLSequence.eHLS_App_alt_28:
			return BLEToyAudioPhrase.eP067;
		case BLEToyHLSequence.eHLS_App_alt_29:
			return BLEToyAudioPhrase.eP068;
		case BLEToyHLSequence.eHLS_App_alt_30:
			return BLEToyAudioPhrase.eP069;
		}
		return BLEToyAudioPhrase.eP001;
	}

	public static float TimeForSequence(BLEToyHLSequence sequence)
	{
		switch (sequence)
		{
		case BLEToyHLSequence.eHLS_Wake_1:
			return 1.623f;
		case BLEToyHLSequence.eHLS_Wake_2:
			return 2.657f;
		case BLEToyHLSequence.eHLS_Wake_4:
			return 1.326f;
		case BLEToyHLSequence.eHLS_Wake_5:
			return 1.749f;
		case BLEToyHLSequence.eHLS_IdlePhrase_2:
			return 2.594f;
		case BLEToyHLSequence.eHLS_IdlePhrase_3:
			return 1.805f;
		case BLEToyHLSequence.eHLS_IdlePhrase_5:
			return 3.737f;
		case BLEToyHLSequence.eHLS_IdlePhrase_6:
			return 5.369f;
		case BLEToyHLSequence.eHLS_IdlePhrase_7:
			return 5.195f;
		case BLEToyHLSequence.eHLS_IdlePhrase_8:
			return 2.13f;
		case BLEToyHLSequence.eHLS_IdlePhrase_9:
			return 2.03f;
		case BLEToyHLSequence.eHLS_IdlePhrase_10:
			return 1.135f;
		case BLEToyHLSequence.eHLS_IdlePhrase_12:
			return 2.982f;
		case BLEToyHLSequence.eHLS_IdlePhrase_13:
			return 3.499f;
		case BLEToyHLSequence.eHLS_IdlePhrase_14:
			return 4.471f;
		case BLEToyHLSequence.eHLS_IdlePhrase_15:
			return 3.266f;
		case BLEToyHLSequence.eHLS_IdlePhrase_16:
			return 3.938f;
		case BLEToyHLSequence.eHLS_IdlePhrase_17:
			return 3.822f;
		case BLEToyHLSequence.eHLS_IdlePhrase_18:
			return 3.455f;
		case BLEToyHLSequence.eHLS_IdlePhrase_19:
			return 4.739f;
		case BLEToyHLSequence.eHLS_IdlePhrase_20:
			return 4.367f;
		case BLEToyHLSequence.eHLS_IdlePhrase_22:
			return 4.403f;
		case BLEToyHLSequence.eHLS_IdlePhrase_23:
			return 4.84f;
		case BLEToyHLSequence.eHLS_IdlePhrase_24:
			return 7.022f;
		case BLEToyHLSequence.eHLS_IdlePhrase_25:
			return 4.83f;
		case BLEToyHLSequence.eHLS_IdlePhrase_26:
			return 7.281f;
		case BLEToyHLSequence.eHLS_IdlePhrase_27:
			return 3.185f;
		case BLEToyHLSequence.eHLS_IdleInstruct_1:
			return 4.867f;
		case BLEToyHLSequence.eHLS_IdleInstruct_2:
			return 2.75f;
		case BLEToyHLSequence.eHLS_IdleInstruct_4:
			return 4.768f;
		case BLEToyHLSequence.eHLS_IdleInstruct_6:
			return 4.67f;
		case BLEToyHLSequence.eHLS_IdleInstruct_7:
			return 6.832f;
		case BLEToyHLSequence.eHLS_IdleInstruct_9:
			return 4.389f;
		case BLEToyHLSequence.eHLS_Sleep_1:
			return 2.498f;
		case BLEToyHLSequence.eHLS_Sleep_2:
			return 3.078f;
		case BLEToyHLSequence.eHLS_Sleep_3:
			return 3.291f;
		case BLEToyHLSequence.eHLS_Sleep_4:
			return 4.028f;
		case BLEToyHLSequence.eHLS_Sleep_5:
			return 3.824f;
		case BLEToyHLSequence.eHLS_Sleep_6:
			return 2.812f;
		case BLEToyHLSequence.eHLS_Sleep_7:
			return 3.697f;
		case BLEToyHLSequence.eHLS_ConnectStart_1:
			return 2.222f;
		case BLEToyHLSequence.eHLS_ConnectStart_2:
			return 1.989f;
		case BLEToyHLSequence.eHLS_ConnectStart_3:
			return 1.202f;
		case BLEToyHLSequence.eHLS_ConnectStart_4:
			return 1.284f;
		case BLEToyHLSequence.eHLS_ConnectStart_5:
			return 2.744f;
		case BLEToyHLSequence.eHLS_DanceIntro_1:
			return 1.228f;
		case BLEToyHLSequence.eHLS_DanceIntro_2:
			return 1.264f;
		case BLEToyHLSequence.eHLS_DanceIntro_3:
			return 1.761f;
		case BLEToyHLSequence.eHLS_DanceName_1:
			return 1.493f;
		case BLEToyHLSequence.eHLS_DanceName_2:
			return 1.817f;
		case BLEToyHLSequence.eHLS_DanceName_4:
			return 1.558f;
		case BLEToyHLSequence.eHLS_DanceName_5:
			return 1.876f;
		case BLEToyHLSequence.eHLS_DanceName_6:
			return 1.639f;
		case BLEToyHLSequence.eHLS_DanceName_7:
			return 1.349f;
		case BLEToyHLSequence.eHLS_DanceName_8:
			return 1.699f;
		case BLEToyHLSequence.eHLS_DanceName_9:
			return 1.714f;
		case BLEToyHLSequence.eHLS_DanceName_10:
			return 1.785f;
		case BLEToyHLSequence.eHLS_DanceName_11_ALT:
			return 1.846f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1:
			return 1.638f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First:
			return 2.579f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final:
			return 2.59f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then:
			return 2.313f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Like:
			return 2.576f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1_ALTA:
			return 2.152f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTA:
			return 3.033f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTA:
			return 3.104f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTA:
			return 2.867f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Like_ALTA:
			return 3.19f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1_ALTB:
			return 1.736f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1First_ALTB:
			return 2.617f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Final_ALTB:
			return 2.688f;
		case BLEToyHLSequence.eHLS_DanceInstruct_1Then_ALTB:
			return 2.451f;
		case BLEToyHLSequence.eHLS_DanceInstruct_2:
			return 1.955f;
		case BLEToyHLSequence.eHLS_DanceInstruct_2First:
			return 2.836f;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Final:
			return 2.907f;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Then:
			return 2.775f;
		case BLEToyHLSequence.eHLS_DanceInstruct_2Like:
			return 3.011f;
		case BLEToyHLSequence.eHLS_DanceInstruct_3:
			return 3.732f;
		case BLEToyHLSequence.eHLS_DanceInstruct_3First:
			return 4.613f;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Final:
			return 4.684f;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Then:
			return 4.447f;
		case BLEToyHLSequence.eHLS_DanceInstruct_3Like:
			return 4.77f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4:
			return 4.028f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4First:
			return 4.909f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Final:
			return 4.98f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Next:
			return 4.849f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Like:
			return 5.085f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4_ALT:
			return 1.442f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4First_ALT:
			return 2.679f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Final_ALT:
			return 2.75f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Next_ALT:
			return 2.539f;
		case BLEToyHLSequence.eHLS_DanceInstruct_4Like_ALT:
			return 2.498f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5:
			return 2.139f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First:
			return 3.019f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final:
			return 3.219f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then:
			return 2.853f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like:
			return 3.176f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5_ALTA:
			return 2.581f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTA:
			return 3.422f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTA:
			return 3.533f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTA:
			return 3.296f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTA:
			return 3.619f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5_ALTB:
			return 1.96f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5First_ALTB:
			return 2.775f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Final_ALTB:
			return 2.846f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Then_ALTB:
			return 2.675f;
		case BLEToyHLSequence.eHLS_DanceInstruct_5Like_ALTB:
			return 2.998f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6:
			return 1.96f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6First:
			return 2.841f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Final:
			return 3.3f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Next:
			return 3.136f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Like:
			return 3.372f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6_ALT:
			return 1.737f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6First_ALT:
			return 2.834f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Final_ALT:
			return 2.689f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Next_ALT:
			return 2.774f;
		case BLEToyHLSequence.eHLS_DanceInstruct_6Like_ALT:
			return 2.793f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7:
			return 2.097f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First:
			return 2.978f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final:
			return 3.049f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then:
			return 2.812f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like:
			return 3.135f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7_ALTA:
			return 1.981f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTA:
			return 2.862f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTA:
			return 2.933f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTA:
			return 2.656f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTA:
			return 3.019f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7_ALTB:
			return 1.097f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7First_ALTB:
			return 2.81f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Final_ALTB:
			return 2.881f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Then_ALTB:
			return 2.644f;
		case BLEToyHLSequence.eHLS_DanceInstruct_7Like_ALTB:
			return 2.967f;
		case BLEToyHLSequence.eHLS_DanceInstruct_8:
			return 2.153f;
		case BLEToyHLSequence.eHLS_DanceInstruct_8First:
			return 3.034f;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Final:
			return 3.105f;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Next:
			return 2.974f;
		case BLEToyHLSequence.eHLS_DanceInstruct_8Like:
			return 3.209f;
		case BLEToyHLSequence.eHLS_DanceInstruct_9:
			return 1.925f;
		case BLEToyHLSequence.eHLS_DanceInstruct_9First:
			return 2.806f;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Final:
			return 2.501f;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Then:
			return 2.264f;
		case BLEToyHLSequence.eHLS_DanceInstruct_9Like:
			return 2.963f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10:
			return 1.637f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10First:
			return 2.458f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Final:
			return 2.873f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Next:
			return 2.458f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Like:
			return 2.694f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10_ALT:
			return 2.514f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10First_ALT:
			return 3.395f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Final_ALT:
			return 3.466f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Next_ALT:
			return 2.938f;
		case BLEToyHLSequence.eHLS_DanceInstruct_10Like_ALT:
			return 3.174f;
		case BLEToyHLSequence.eHLS_DanceInstruct_11:
			return 1.85f;
		case BLEToyHLSequence.eHLS_DanceInstruct_11First:
			return 3.025f;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Final:
			return 3.096f;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Then:
			return 2.819f;
		case BLEToyHLSequence.eHLS_DanceInstruct_11Like:
			return 2.888f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Spin_1:
			return 2.757f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Spin_1_ALT:
			return 2.36f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1:
			return 1.974f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1:
			return 2.855f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1:
			return 3.288f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1:
			return 2.678f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1:
			return 3.031f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTA:
			return 2.254f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1B:
			return 3.135f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1B:
			return 3.42f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTA:
			return 2.958f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTA:
			return 3.311f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RS_1_ALTB:
			return 1.918f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFirst_1C:
			return 2.799f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSFinal_1C:
			return 3.812f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSNow_1_ALTB:
			return 2.622f;
		case BLEToyHLSequence.eHLS_DanceInstruct_RSLike_1_ALTB:
			return 2.975f;
		case BLEToyHLSequence.eHLS_DanceInstruct_SpinAgain_1:
			return 1.494f;
		case BLEToyHLSequence.eHLS_DanceInstruct_SpinOther_1:
			return 1.903f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1:
			return 1.677f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Curtsy_1_ALT:
			return 1.266f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Fwd_1:
			return 1.209f;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdFirst_1:
			return 1.943f;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdFinal_1:
			return 2.161f;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdNow_1:
			return 1.913f;
		case BLEToyHLSequence.eHLS_DanceInstruct_FwdThen_1:
			return 2.236f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Back_1:
			return 1.046f;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackFirst_1:
			return 1.877f;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackFinal_1:
			return 1.998f;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackNow_1:
			return 1.75f;
		case BLEToyHLSequence.eHLS_DanceInstruct_BackThen_1:
			return 2.013f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Turn_1:
			return 1.364f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1:
			return 2.245f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1:
			return 2.316f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1:
			return 2.068f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1:
			return 2.47f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Turn_1_ALT:
			return 1.586f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFirst_1_ALT:
			return 2.467f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnFinal_1_ALT:
			return 2.538f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnNow_1_ALT:
			return 2.29f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnThen_1_ALT:
			return 2.7f;
		case BLEToyHLSequence.eHLS_DanceInstruct_FaceFwd_1:
			return 1.399f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1:
			return 2.348f;
		case BLEToyHLSequence.eHLS_DanceInstruct_TurnOther_1_ALT:
			return 2.318f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Arms_1:
			return 2.519f;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsFirst_1:
			return 3.063f;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsNow_1:
			return 3.31f;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsThen_1:
			return 2.835f;
		case BLEToyHLSequence.eHLS_DanceInstruct_ArmsFinal_1:
			return 3.147f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Move_1:
			return 1.693f;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveFirst_1:
			return 2.534f;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveNow_1:
			return 2.357f;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveThen_1:
			return 1.788f;
		case BLEToyHLSequence.eHLS_DanceInstruct_MoveFinal_1:
			return 2.075f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_1:
			return 2.494f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_2:
			return 2.904f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Perform_3:
			return 1.347f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Generic_1:
			return 1.225f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Generic_2:
			return 1.342f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1:
			return 3.697f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Repeat_1_ALT:
			return 1.991f;
		case BLEToyHLSequence.eHLS_DanceInstruct_Connect_1:
			return 0.692f;
		case BLEToyHLSequence.eHLS_Encourage_1:
			return 2.238f;
		case BLEToyHLSequence.eHLS_Encourage_2:
			return 2.146f;
		case BLEToyHLSequence.eHLS_Encourage_3:
			return 1.895f;
		case BLEToyHLSequence.eHLS_Encourage_4:
			return 1.676f;
		case BLEToyHLSequence.eHLS_Encourage_5:
			return 2.725f;
		case BLEToyHLSequence.eHLS_Encourage_6:
			return 2.508f;
		case BLEToyHLSequence.eHLS_Encourage_7:
			return 2.136f;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_1:
			return 4.715f;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_2:
			return 5.647f;
		case BLEToyHLSequence.eHLS_PerformAgainPrompt_3:
			return 4.984f;
		case BLEToyHLSequence.eHLS_LiftPhrase_1:
			return 2.315f;
		case BLEToyHLSequence.eHLS_LiftPhrase_2:
			return 3.163f;
		case BLEToyHLSequence.eHLS_LiftPhrase_4:
			return 2.167f;
		case BLEToyHLSequence.eHLS_LiftPhrase_5:
			return 1.707f;
		case BLEToyHLSequence.eHLS_DanceTogether_1:
			return 2.334f;
		case BLEToyHLSequence.eHLS_DanceTogether_2:
			return 1.069f;
		case BLEToyHLSequence.eHLS_DanceTogether_3:
			return 1.868f;
		case BLEToyHLSequence.eHLS_DanceTogether_4:
			return 2.735f;
		case BLEToyHLSequence.eHLS_DanceTogether_5:
			return 2.176f;
		case BLEToyHLSequence.eHLS_DanceTogether_6:
			return 2.835f;
		case BLEToyHLSequence.eHLS_DanceTogether_7:
			return 2.986f;
		case BLEToyHLSequence.eHLS_DanceTogether_8:
			return 3.821f;
		case BLEToyHLSequence.eHLS_DanceBreak_1:
			return 2.593f;
		case BLEToyHLSequence.eHLS_DanceBreak_2:
			return 3.468f;
		case BLEToyHLSequence.eHLS_AppConnect_1:
			return 1.538f;
		case BLEToyHLSequence.eHLS_ButtonPress_1:
			return 0.617f;
		case BLEToyHLSequence.eHLS_SleepButtonPress_1:
			return 1.535f;
		case BLEToyHLSequence.eHLS_DanceRoutine_1:
			return 20.794f;
		case BLEToyHLSequence.eHLS_DanceRoutine_2:
			return 16.788f;
		case BLEToyHLSequence.eHLS_DanceRoutine_3:
			return 22.866f;
		case BLEToyHLSequence.eHLS_DanceRoutine_4:
			return 23.11f;
		case BLEToyHLSequence.eHLS_DanceRoutine_5:
			return 14.756f;
		case BLEToyHLSequence.eHLS_DanceRoutine_6:
			return 14.981f;
		case BLEToyHLSequence.eHLS_DanceRoutine_7:
			return 17.542f;
		case BLEToyHLSequence.eHLS_DanceRoutine_8:
			return 17.566f;
		case BLEToyHLSequence.eHLS_DanceRoutine_9:
			return 17.455f;
		case BLEToyHLSequence.eHLS_DanceRoutine_10:
			return 16.515f;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_1:
			return 2.904f;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_2:
			return 2.478f;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_3:
			return 4.748f;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_4:
			return 3.492f;
		case BLEToyHLSequence.eHLS_LessonPerformIntro_6:
			return 5.087f;
		case BLEToyHLSequence.eHLS_ShortInstruct_1:
			return 1.324f;
		case BLEToyHLSequence.eHLS_ShortInstruct_1_ALTA:
			return 1.069f;
		case BLEToyHLSequence.eHLS_ShortInstruct_2:
			return 1.337f;
		case BLEToyHLSequence.eHLS_ShortInstruct_3:
			return 2.643f;
		case BLEToyHLSequence.eHLS_ShortInstruct_4:
			return 2.449f;
		case BLEToyHLSequence.eHLS_ShortInstruct_4_ALT:
			return 1.252f;
		case BLEToyHLSequence.eHLS_ShortInstruct_5:
			return 0.947f;
		case BLEToyHLSequence.eHLS_ShortInstruct_6:
			return 1.24f;
		case BLEToyHLSequence.eHLS_ShortInstruct_7:
			return 1.452f;
		case BLEToyHLSequence.eHLS_ShortInstruct_7_ALTB:
			return 1.097f;
		case BLEToyHLSequence.eHLS_ShortInstruct_8:
			return 1.266f;
		case BLEToyHLSequence.eHLS_ShortInstruct_9:
			return 1.451f;
		case BLEToyHLSequence.eHLS_ShortInstruct_10_ALT:
			return 1.704f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Spin_1:
			return 1.315f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Spin_1_ALT:
			return 1.46f;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1:
			return 1.974f;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1_ALTA:
			return 2.254f;
		case BLEToyHLSequence.eHLS_ShortInstruct_RS_1_ALTB:
			return 1.918f;
		case BLEToyHLSequence.eHLS_ShortInstruct_SpinAgain_1:
			return 1.439f;
		case BLEToyHLSequence.eHLS_ShortInstruct_SpinOther_1:
			return 1.665f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Curtsy_1:
			return 1.677f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Curtsy_1_ALT:
			return 1.266f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Fwd_1:
			return 1.209f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Back_1:
			return 1.046f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Turn_1:
			return 1.364f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Turn_1_ALT:
			return 1.586f;
		case BLEToyHLSequence.eHLS_ShortInstruct_FaceFwd_1:
			return 1.373f;
		case BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1:
			return 1.659f;
		case BLEToyHLSequence.eHLS_ShortInstruct_TurnOther_1_ALT:
			return 1.629f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Move_1:
			return 1.123f;
		case BLEToyHLSequence.eHLS_ShortInstruct_MoveThen_1:
			return 1.788f;
		case BLEToyHLSequence.eHLS_ShortInstruct_Generic_2:
			return 1.342f;
		case BLEToyHLSequence.eHLS_App_Phrase_1:
			return 3.218f;
		case BLEToyHLSequence.eHLS_App_Phrase_2:
			return 3.389f;
		case BLEToyHLSequence.eHLS_App_Phrase_3:
			return 3.744f;
		case BLEToyHLSequence.eHLS_App_Phrase_4:
			return 4.365f;
		case BLEToyHLSequence.eHLS_App_Phrase_5:
			return 1.725f;
		case BLEToyHLSequence.eHLS_App_Phrase_6:
			return 3.727f;
		case BLEToyHLSequence.eHLS_App_Phrase_7:
			return 3.387f;
		case BLEToyHLSequence.eHLS_App_Phrase_8:
			return 3.493f;
		case BLEToyHLSequence.eHLS_App_Phrase_9:
			return 3.593f;
		case BLEToyHLSequence.eHLS_App_Phrase_10:
			return 5.738f;
		case BLEToyHLSequence.eHLS_App_Phrase_11:
			return 1.84f;
		case BLEToyHLSequence.eHLS_App_Phrase_12:
			return 2.522f;
		case BLEToyHLSequence.eHLS_App_Phrase_13:
			return 3.287f;
		case BLEToyHLSequence.eHLS_App_Phrase_14:
			return 1.361f;
		case BLEToyHLSequence.eHLS_App_Phrase_15:
			return 2.061f;
		case BLEToyHLSequence.eHLS_App_Phrase_16:
			return 1.784f;
		case BLEToyHLSequence.eHLS_App_Phrase_17:
			return 1.901f;
		case BLEToyHLSequence.eHLS_App_Phrase_18:
			return 0.972f;
		case BLEToyHLSequence.eHLS_App_Phrase_19:
			return 1.412f;
		case BLEToyHLSequence.eHLS_App_Phrase_20:
			return 1.337f;
		case BLEToyHLSequence.eHLS_App_Phrase_21:
			return 1.28f;
		case BLEToyHLSequence.eHLS_App_Phrase_22:
			return 1.892f;
		case BLEToyHLSequence.eHLS_App_Phrase_23:
			return 5.223f;
		case BLEToyHLSequence.eHLS_App_Phrase_24:
			return 1.549f;
		case BLEToyHLSequence.eHLS_App_Phrase_25:
			return 2.047f;
		case BLEToyHLSequence.eHLS_App_Phrase_26:
			return 1.415f;
		case BLEToyHLSequence.eHLS_App_Phrase_27:
			return 4.604f;
		case BLEToyHLSequence.eHLS_App_Phrase_28:
			return 2.058f;
		case BLEToyHLSequence.eHLS_App_Phrase_29:
			return 2.451f;
		case BLEToyHLSequence.eHLS_App_Phrase_30:
			return 2.08f;
		case BLEToyHLSequence.eHLS_App_Phrase_31:
			return 2.463f;
		case BLEToyHLSequence.eHLS_App_Phrase_32:
			return 2.62f;
		case BLEToyHLSequence.eHLS_App_Phrase_33:
			return 2.591f;
		case BLEToyHLSequence.eHLS_App_Phrase_34:
			return 4.169f;
		case BLEToyHLSequence.eHLS_App_Phrase_34_alt1:
			return 3.436f;
		case BLEToyHLSequence.eHLS_App_Phrase_34_alt2:
			return 4.655f;
		case BLEToyHLSequence.eHLS_App_Phrase_35:
			return 2.824f;
		case BLEToyHLSequence.eHLS_App_Phrase_36:
			return 2.307f;
		case BLEToyHLSequence.eHLS_App_Phrase_37:
			return 1.667f;
		case BLEToyHLSequence.eHLS_App_Phrase_38:
			return 1.623f;
		case BLEToyHLSequence.eHLS_App_Phrase_39:
			return 2.913f;
		case BLEToyHLSequence.eHLS_App_Phrase_40:
			return 2.779f;
		case BLEToyHLSequence.eHLS_App_Phrase_41:
			return 2.724f;
		case BLEToyHLSequence.eHLS_App_Phrase_42:
			return 3.59f;
		case BLEToyHLSequence.eHLS_App_Phrase_43:
			return 3.476f;
		case BLEToyHLSequence.eHLS_App_Phrase_44:
			return 3.629f;
		case BLEToyHLSequence.eHLS_App_Phrase_45:
			return 3.853f;
		case BLEToyHLSequence.eHLS_App_Phrase_46:
			return 3.565f;
		case BLEToyHLSequence.eHLS_App_Phrase_47:
			return 3.531f;
		case BLEToyHLSequence.eHLS_App_Phrase_48:
			return 2.579f;
		case BLEToyHLSequence.eHLS_App_Phrase_49:
			return 3.812f;
		case BLEToyHLSequence.eHLS_App_Phrase_50:
			return 2.304f;
		case BLEToyHLSequence.eHLS_App_Phrase_51:
			return 2.584f;
		case BLEToyHLSequence.eHLS_App_Phrase_52:
			return 4.07f;
		case BLEToyHLSequence.eHLS_App_Phrase_53:
			return 2.059f;
		case BLEToyHLSequence.eHLS_App_Phrase_54:
			return 3.111f;
		case BLEToyHLSequence.eHLS_App_Phrase_55:
			return 3.649f;
		case BLEToyHLSequence.eHLS_App_Phrase_56:
			return 4.18f;
		case BLEToyHLSequence.eHLS_App_Phrase_57:
			return 4.175f;
		case BLEToyHLSequence.eHLS_App_Phrase_58:
			return 4.686f;
		case BLEToyHLSequence.eHLS_App_Phrase_59:
			return 4.905f;
		case BLEToyHLSequence.eHLS_App_Phrase_60:
			return 1.898f;
		case BLEToyHLSequence.eHLS_App_Phrase_61:
			return 1.668f;
		case BLEToyHLSequence.eHLS_App_Phrase_62:
			return 1.872f;
		case BLEToyHLSequence.eHLS_App_Phrase_63:
			return 2.857f;
		case BLEToyHLSequence.eHLS_App_Phrase_64:
			return 2.399f;
		case BLEToyHLSequence.eHLS_App_Phrase_65:
			return 2.993f;
		case BLEToyHLSequence.eHLS_App_Phrase_66:
			return 2.797f;
		case BLEToyHLSequence.eHLS_App_Phrase_67:
			return 2.826f;
		case BLEToyHLSequence.eHLS_App_Phrase_68:
			return 2.364f;
		case BLEToyHLSequence.eHLS_App_Phrase_69:
			return 2.557f;
		case BLEToyHLSequence.eHLS_App_Phrase_70:
			return 2.802f;
		case BLEToyHLSequence.eHLS_App_Phrase_71:
			return 3.02f;
		case BLEToyHLSequence.eHLS_App_Phrase_72:
			return 2.877f;
		case BLEToyHLSequence.eHLS_App_Phrase_73:
			return 2.731f;
		case BLEToyHLSequence.eHLS_App_Phrase_74:
			return 2.197f;
		case BLEToyHLSequence.eHLS_App_Phrase_75:
			return 2.98f;
		case BLEToyHLSequence.eHLS_App_Phrase_76:
			return 2.519f;
		case BLEToyHLSequence.eHLS_App_Phrase_77:
			return 2.067f;
		case BLEToyHLSequence.eHLS_App_Phrase_78:
			return 2.292f;
		case BLEToyHLSequence.eHLS_App_Phrase_79:
			return 3.063f;
		case BLEToyHLSequence.eHLS_App_Phrase_80:
			return 2.308f;
		case BLEToyHLSequence.eHLS_App_Phrase_81:
			return 1.964f;
		case BLEToyHLSequence.eHLS_App_Phrase_82:
			return 2.309f;
		case BLEToyHLSequence.eHLS_App_Phrase_83:
			return 2.725f;
		case BLEToyHLSequence.eHLS_App_Phrase_84:
			return 2.249f;
		case BLEToyHLSequence.eHLS_App_Phrase_85:
			return 3.148f;
		case BLEToyHLSequence.eHLS_App_Phrase_86:
			return 2.126f;
		case BLEToyHLSequence.eHLS_App_Phrase_87:
			return 2.799f;
		case BLEToyHLSequence.eHLS_App_Phrase_88:
			return 3.557f;
		case BLEToyHLSequence.eHLS_App_Phrase_89:
			return 2.621f;
		case BLEToyHLSequence.eHLS_App_Phrase_90:
			return 2.57f;
		case BLEToyHLSequence.eHLS_App_Phrase_91:
			return 3.511f;
		case BLEToyHLSequence.eHLS_App_Phrase_92:
			return 2.075f;
		case BLEToyHLSequence.eHLS_App_Phrase_93:
			return 1.914f;
		case BLEToyHLSequence.eHLS_App_Phrase_94:
			return 3.436f;
		case BLEToyHLSequence.eHLS_App_Phrase_95:
			return 1.951f;
		case BLEToyHLSequence.eHLS_App_Phrase_96:
			return 3.675f;
		case BLEToyHLSequence.eHLS_App_Phrase_97:
			return 4.583f;
		case BLEToyHLSequence.eHLS_App_Phrase_98:
			return 2.164f;
		case BLEToyHLSequence.eHLS_App_Phrase_99:
			return 1.815f;
		case BLEToyHLSequence.eHLS_App_Phrase_100:
			return 1.686f;
		case BLEToyHLSequence.eHLS_App_Phrase_101:
			return 1.341f;
		case BLEToyHLSequence.eHLS_App_Phrase_102:
			return 2.708f;
		case BLEToyHLSequence.eHLS_App_Phrase_103:
			return 3.483f;
		case BLEToyHLSequence.eHLS_App_alt_1:
			return 2.656f;
		case BLEToyHLSequence.eHLS_App_alt_2:
			return 2.258f;
		case BLEToyHLSequence.eHLS_App_alt_3:
			return 1.843f;
		case BLEToyHLSequence.eHLS_App_alt_4:
			return 4.558f;
		case BLEToyHLSequence.eHLS_App_alt_5:
			return 4.916f;
		case BLEToyHLSequence.eHLS_App_alt_6:
			return 4.564f;
		case BLEToyHLSequence.eHLS_App_alt_7:
			return 5.636f;
		case BLEToyHLSequence.eHLS_App_alt_8:
			return 4.687f;
		case BLEToyHLSequence.eHLS_App_alt_9:
			return 2.62f;
		case BLEToyHLSequence.eHLS_App_alt_10:
			return 5.009f;
		case BLEToyHLSequence.eHLS_App_alt_11:
			return 5.932f;
		case BLEToyHLSequence.eHLS_App_alt_12:
			return 6.438f;
		case BLEToyHLSequence.eHLS_App_alt_13:
			return 2.494f;
		case BLEToyHLSequence.eHLS_App_alt_14:
			return 2.951f;
		case BLEToyHLSequence.eHLS_App_alt_15:
			return 0.935f;
		case BLEToyHLSequence.eHLS_App_alt_16:
			return 1.665f;
		case BLEToyHLSequence.eHLS_App_alt_17:
			return 1.895f;
		case BLEToyHLSequence.eHLS_App_alt_18:
			return 2.657f;
		case BLEToyHLSequence.eHLS_App_alt_19:
			return 1.676f;
		case BLEToyHLSequence.eHLS_App_alt_20:
			return 1.221f;
		case BLEToyHLSequence.eHLS_App_alt_21:
			return 1.664f;
		case BLEToyHLSequence.eHLS_App_alt_22:
			return 2.504f;
		case BLEToyHLSequence.eHLS_App_alt_23:
			return 1.997f;
		case BLEToyHLSequence.eHLS_App_alt_24:
			return 1.488f;
		case BLEToyHLSequence.eHLS_App_alt_25:
			return 4.589f;
		case BLEToyHLSequence.eHLS_App_alt_26:
			return 4.037f;
		case BLEToyHLSequence.eHLS_App_alt_27:
			return 3.166f;
		case BLEToyHLSequence.eHLS_App_alt_28:
			return 3.414f;
		case BLEToyHLSequence.eHLS_App_alt_29:
			return 2.022f;
		case BLEToyHLSequence.eHLS_App_alt_30:
			return 2.973f;
		}
		return 0f;
	}
}
