using System;

public enum BLEToySequenceWaitCommand
{
	WAIT_FINISH_HL_SEQUENCE = 1,
	WAIT_FINISH_LED_SEQUENCE,
	WAIT_FINISH_MOTOR_SEQUENCE = 4,
	WAIT_FINISH_CAM_SEEK = 8,
	WAIT_FINISH_HEAD_SEEK = 16,
	WAIT_FINISH_AUDIO_PLAYLIST = 32,
	WAIT_FINISH_MOTOR_2 = 64,
	WAIT_FINISH_MOTOR_3 = 128
}
