using System;

public enum BLEToyInputCode
{
	LVD_ID,
	TEST_KEY_BUTTON_ID,
	LIFT_BUTTON_ID,
	NECKLACE_BUTTON_ID,
	LEFT_ARM_LEAF_1_BUTTON_ID,
	LEFT_ARM_LEAF_2_BUTTON_ID,
	RIGHT_ARM_LEAF_1_BUTTON_ID,
	RIGHT_ARM_LEAF_2_BUTTON_ID,
	LEFT_LEAF_A_BUTTON_ID,
	LEFT_LEAF_B_BUTTON_ID,
	RIGHT_LEAF_A_BUTTON_ID,
	RIGHT_LEAF_B_BUTTON_ID,
	ARM_WIPER_B0_BUTTON_ID,
	ARM_WIPER_B1_BUTTON_ID,
	ARM_WIPER_B2_BUTTON_ID,
	ARM_WIPER_B3_BUTTON_ID
}
